parameters:
    pimee_workflow.repository.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Doctrine\Repository\MongoDBODM\PropositionRepository

services:
    pimee_workflow.object_manager.proposition:
        alias: doctrine.odm.mongodb.document_manager
