parameters:
    pimee_workflow.repository.product_draft.class:       PimEnterprise\Bundle\WorkflowBundle\Doctrine\MongoDBODM\ProductDraftRepository
    pimee_workflow.repository.published_product.class: PimEnterprise\Bundle\WorkflowBundle\Doctrine\MongoDBODM\PublishedProductRepository
    pimee_workflow.repository.product_draft_ownership.class: PimEnterprise\Bundle\WorkflowBundle\Doctrine\MongoDBODM\ProductDraftOwnershipRepository
    pimee_workflow.subscriber.synchronize_product_draft_categories.class: PimEnterprise\Bundle\WorkflowBundle\EventSubscriber\ProductDraft\SynchronizeProductDraftCategoriesSubscriber

services:
    pimee_workflow.object_manager.product_draft:
        alias: doctrine.odm.mongodb.document_manager

    pimee_workflow.repository.published_product:
        class: %pimee_workflow.repository.published_product.class%
        factory_service: pim_catalog.object_manager.product
        factory_method: getRepository
        arguments: [%pimee_workflow.entity.published_product.class%]
        calls:
            - [setProductQueryFactory, ['@pimee_workflow.doctrine.query.published_product_query_factory']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setAttributeRepository, ['@pim_catalog.repository.attribute']]
            - [setFamilyRepository, ['@pim_catalog.repository.family']]
        tags:
            - { name: 'pim_repository' }

    pimee_workflow.repository.published_product_category:
        class: %pim_catalog.repository.product_category.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - %pimee_workflow.entity.published_product.class%
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.category.class%

    pimee_workflow.repository.published_association:
        alias: pimee_workflow.repository.published_product

    pimee_workflow.repository.product_draft_ownership:
        class: %pimee_workflow.repository.product_draft_ownership.class%
        arguments:
            - '@pimee_workflow.repository.product_draft'
            - '@pimee_security.repository.category_access'

    pimee_workflow.repository.published_product_mass_action:
        class: %pim_catalog.repository.product_mass_action.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - %pimee_workflow.entity.published_product.class%
            - '@pim_catalog.repository.family'
            - '@pimee_workflow.repository.published_product'

    pimee_workflow.subscriber.synchronize_product_draft_categories:
        class: %pimee_workflow.subscriber.synchronize_product_draft_categories.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '%pimee_workflow.model.product_draft.class%'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
            - { name: doctrine.event_subscriber }
