parameters:
    pimee_workflow.repository.proposal.class: PimEnterprise\Bundle\WorkflowBundle\Doctrine\Repository\ORM\ProposalRepository

services:
    pimee_workflow.object_manager.proposal:
        alias: doctrine.orm.entity_manager
