parameters:
    pimee_workflow.repository.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Doctrine\Repository\ORM\PropositionRepository

services:
    pimee_workflow.object_manager.proposition:
        alias: doctrine.orm.entity_manager
