parameters:
    pimee_product_rule.applier.product.class: PimEnterprise\Bundle\ProductRuleBundle\Engine\ProductRuleApplier
    pimee_product_rule.loader.product.class: PimEnterprise\Bundle\ProductRuleBundle\Engine\ProductRuleLoader
    pimee_product_rule.selector.product.class: PimEnterprise\Bundle\ProductRuleBundle\Engine\ProductRuleSelector

services:
    pimee_product_rule.loader.product:
        class: %pimee_product_rule.loader.product.class%
        arguments:
            - @event_dispatcher
            - %pimee_rule_engine.entity.loaded_rule.class%

    pimee_product_rule.selector.product:
        class: %pimee_product_rule.selector.product.class%
        arguments:
            - @pim_catalog.doctrine.query.product_query_factory
            - @pim_catalog.repository.product
            - @event_dispatcher
            - %pimee_rule_engine.entity.rule_subject_set.class%

    pimee_product_rule.applier.product:
        class: %pimee_product_rule.applier.product.class%
        arguments:
            - @pim_catalog.updater.product
            - @event_dispatcher
