parameters:
    pimee_product_rule.loader.product.class: PimEnterprise\Bundle\ProductRuleBundle\Loader\ProductRuleLoader
    pimee_product_rule.runnable.product.class: PimEnterprise\Bundle\ProductRuleBundle\Model\ProductRunnableRule

services:
    pimee_product_rule.loader.product:
        class: %pimee_product_rule.loader.product.class%
        arguments:
            - %pimee_product_rule.runnable.product.class%
            - @pim_catalog.doctrine.query.product_query_builder
            - @pim_catalog.repository.product
        tags:
            - { name: pimee_rule_engine.loader }
