parameters:
    pimee_product_rule.runner.product.class: PimEnterprise\Bundle\ProductRuleBundle\Runner\ProductRuleRunner

services:
    pimee_product_rule.runner.product:
        class: %pimee_product_rule.runner.product.class%
        arguments:
            - @pimee_product_rule.loader.product
            - @pimee_product_rule.selector.product
            - @pimee_product_rule.applier.product
        tags:
            - { name: pimee_rule_engine.runner }
