parameters:
    pimee_product_rule.selector.product.class: PimEnterprise\Bundle\ProductRuleBundle\Selector\ProductRuleSelector

services:
    pimee_product_rule.selector.product:
        class: %pimee_product_rule.selector.product.class%
        arguments:
            - %pimee_rule_engine.entity.rule_subject_set.class%
            - @pim_catalog.doctrine.query.product_query_builder
            - @pim_catalog.repository.product
        tags:
            - { name: pimee_rule_engine.selector }
