datagrid:
    draft-grid:
        options:
            entityHint: proposal
        source:
            type: pimee_datasource_product_draft
            entity: %pimee_workflow.model.product_draft.class%
            repository_method: createProposalDatagridQueryBuilder
        columns:
            product:
                label: pimee_workflow.product_draft.product.label
                type: field
                frontend_type: string
            author:
                label: pimee_workflow.product_draft.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.product_draft.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: expand
            createdAt:
                label: pimee_workflow.product_draft.created
                type: field
                frontend_type: datetime
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_product_draft_approve
                params:
                    - id
                    - dataLocale
            refuse_link:
                type: url
                route: pimee_workflow_product_draft_refuse
                params:
                    - id
                    - dataLocale
        actions:
            approve:
                type: ajax
                label: pimee_workflow.product_draft.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: ajax
                label: pimee_workflow.product_draft.action.refuse
                icon: remove
                link: refuse_link
        filters:
            columns:
                createdAt:
                    type:      date
                    ftype:     date
                    data_name: p.createdAt
                    label:     pimee_workflow.product_draft.created
                autor:
                    type:        choice
                    ftype:       choice
                    data_name:   p.author
                    label:       pimee_workflow.product_draft.author
                    options:
                        field_options:
                            multiple: true
                            choices: '@pimee_datagrid.datagrid.proposal.grid_helper->getAuthorChoices'
        sorters:
            columns:
                author:
                    data_name: author
                createdAt:
                    data_name: createdAt
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    product-draft-grid:
        options:
            entityHint: product_draft
        source:
            type: pimee_datasource_product_draft
            entity: %pimee_workflow.model.product_draft.class%
            repository_method: createDatagridQueryBuilder
        columns:
            author:
                label: pimee_workflow.product_draft.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.product_draft.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.product_draft.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.product_draft.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/product_draft_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_product_draft_approve
                params:
                    - id
                    - dataLocale
            refuse_link:
                type: url
                route: pimee_workflow_product_draft_refuse
                params:
                    - id
                    - dataLocale
        actions:
            approve:
                type: navigate
                label: pimee_workflow.product_draft.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.product_draft.action.refuse
                icon: remove
                link: refuse_link
            remove:
                type: navigate
                label: pimee_workflow.product_draft.action.remove
                icon: trash
                link: refuse_link
        action_configuration: '@pimee_datagrid.datagrid.product_draft.grid_helper->getActionConfigurationClosure'
        filters:
            columns:
                status:
                    type:        product_draft_choice
                    ftype:       choice
                    data_name:   status
                    label:       pimee_workflow.product_draft.status.label
                    options:
                        field_options:
                            multiple: false
                            choices: '@pimee_datagrid.datagrid.product_draft.grid_helper->getStatusChoices'
        sorters:
            columns:
                author:
                    data_name: author
                status:
                    data_name: status
                createdAt:
                    data_name: createdAt
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
