datagrid:
    proposition-grid:
        options:
            entityHint: proposition
        source:
            type: pim_datasource_smart
            entity: %pimee_workflow.model.proposition.class%
            repository_method: createDatagridQueryBuilder
        columns:
            author:
                label: pimee_workflow.proposition.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.proposition.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.proposition.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.proposition.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/proposition_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_proposition_approve
                params:
                    - id
                    - dataLocale
            refuse_link:
                type: url
                route: pimee_workflow_proposition_refuse
                params:
                    - id
                    - dataLocale
        actions:
            approve:
                type: navigate
                label: pimee_workflow.proposition.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.proposition.action.refuse
                icon: remove
                link: refuse_link
            remove:
                type: navigate
                label: pimee_workflow.proposition.action.remove
                icon: trash
                link: refuse_link
        action_configuration: '@pimee_workflow.datagrid.proposition_grid_helper->getActionConfigurationClosure'
        filters:
            columns:
                status:
                    type:        proposition_choice
                    parent_type: choice
                    data_name:   status
                    label:       pimee_workflow.proposition.status.label
                    options:
                        field_options:
                            multiple: true
                            choices: '@pimee_workflow.datagrid.proposition_grid_helper->getStatusChoices'
        sorters:
            columns:
                author:
                    data_name: author
                status:
                    data_name: status
                createdAt:
                    data_name: createdAt
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
