parameters:
    pim_datagrid.datagrid.product.context_configurator.class:       PimEnterprise\Bundle\DataGridBundle\Datagrid\Product\ContextConfigurator
    pimee_datagrid.datagrid.product.row_actions_configurator.class: PimEnterprise\Bundle\DataGridBundle\Datagrid\Product\RowActionsConfigurator

services:
    pim_datagrid.datagrid.product.context_configurator:
        class: %pim_datagrid.datagrid.product.context_configurator.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@oro_datagrid.datagrid.request_params'
            - '@pim_user.context.user'
            - '@pim_datagrid.repository.datagrid_view'
            - '@pimee_security.repository.attribute_group_access'
        calls:
            - [setRequest, ['@?request=']]

    pimee_datagrid.datagrid.product.row_actions_configurator:
        class: %pimee_datagrid.datagrid.product.row_actions_configurator.class%
        arguments:
            - '@pim_datagrid.datagrid.product.configuration_registry'
            - '@security.context'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.locale'
