services:
    pim_datagrid.extension.selector.orm_selector:
        class: %pim_datagrid.extension.selector.orm_selector.class%
        arguments:
            - %akeneo_storage_utils.storage_driver%
            - '@oro_datagrid.datagrid.request_params'
        calls:
            - [addEligibleDatasource, ['pim_datasource_product']]
            - [addEligibleDatasource, ['pimee_datasource_published_product']]
        tags:
             - { name: oro_datagrid.extension }
