services:
    pimee_datagrid.datasource.result_record.hydrator.product_history:
        class: %pimee_datagrid.datasource.result_record.hydrator.product_history.class%
        arguments:
            - @pimee_workflow.repository.published_product

    pim_datagrid.datasource.result_record.hydrator.proposition:
        class: %pimee_datagrid.datasource.result_record.hydrator.proposition.class%
        arguments:
          - '@oro_datagrid.datagrid.request_params'
        calls:
            - [setRequest, ['@?request=']]
