parameters:
    pim_datagrid.manager.datagrid_view.class: PimEnterprise\Bundle\DataGridBundle\Manager\DatagridViewManager

services:
    pim_datagrid.manager.datagrid_view:
        class: %pim_datagrid.manager.datagrid_view.class%
        arguments:
            - '@pim_datagrid.repository.datagrid_view'
            - '@oro_datagrid.datagrid.manager'
            - '@security.context'
