services:
    pimee_datagrid.extension.sorter.proposition.field_sorter:
        class: %pimee_datagrid.extension.sorter.proposition.field_sorter.class%
        tags:
            - { name: pim_datagrid.extension.sorter, type: proposition_field }
