parameters:
    pimee_filter.proposition_choice_filter.class: PimEnterprise\Bundle\FilterBundle\Filter\Proposition\ChoiceFilter

services:
    pimee_filter.proposition_choice_filter:
        class: %pimee_filter.proposition_choice_filter.class%
        arguments:
            - '@form.factory'
            - '@pimee_filter.proposition_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: proposition_choice }
