parameters:
    pimee_filter.proposition_choice_filter.class: PimEnterprise\Bundle\FilterBundle\Filter\Proposition\ChoiceFilter
    pim_filter.product_category_filter.class:     PimEnterprise\Bundle\FilterBundle\Filter\Product\CategoryFilter
    pimee_filter.product_permission_filter.class: PimEnterprise\Bundle\FilterBundle\Filter\Product\PermissionFilter

services:
    pimee_filter.proposition_choice_filter:
        class: %pimee_filter.proposition_choice_filter.class%
        arguments:
            - '@form.factory'
            - '@pimee_filter.proposition_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: proposition_choice }

    pimee_filter.product_permission_filter:
        class: %pimee_filter.product_permission_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@security.context'
            - '@pim_catalog.repository.product_category'
            - '@pimee_security.repository.category_access'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_permission }

    pim_filter.product_category_filter:
        class: %pim_filter.product_category_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@pim_catalog.manager.product_category'
            - '@security.context'
            - '@pimee_security.repository.category_access'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_category }

    pimee_filter.published_product_category_filter:
        class: %pim_filter.product_category_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@pimee_workflow.manager.published_product_category'
            - '@security.context'
            - '@pimee_security.repository.category_access'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: published_product_category }
