parameters:
    pimee_filter.proposition_utility.class: PimEnterprise\Bundle\FilterBundle\Filter\PropositionFilterUtility

services:
    pimee_filter.proposition_utility:
        class: %pimee_filter.proposition_utility.class%
        arguments:
            - '@pimee_workflow.repository.proposition'
