parameters:
    pimee_import_export.form.type.job_profile_permissions.class:       PimEnterprise\Bundle\ImportExportBundle\Form\Type\JobProfilePermissionsType
    pimee_import_export.form.subscriber.job_profile_permissions.class: PimEnterprise\Bundle\ImportExportBundle\Form\Subscriber\JobProfilePermissionsSubscriber

services:
    pim_import_export.form.type.job_instance:
        class: %pim_import_export.form.type.job_instance.class%
        arguments:
            - '@akeneo_batch.connectors'
        tags:
            - { name: form.type, alias: pim_import_export_job_instance }
        calls:
            - [addEventSubscriber, ['@pimee_import_export.form_subcriber.job_profile_permissions']]

    pimee_import_export.form_subcriber.job_profile_permissions:
        class: %pimee_import_export.form.subscriber.job_profile_permissions.class%
        arguments:
            - '@pimee_security.manager.job_profile_access'
            - '@oro_security.security_facade'

    pimee_import_export.form.subscriber.job_profile_permissions:
        class: %pimee_import_export.form.type.job_profile_permissions.class%
        tags:
            - { name: form.type, alias: pimee_import_export_job_profile_permissions }
