connector:
    name: Data fixtures
    jobs:
        fixtures_attribute_group_access_yml:
            title: pim_installer.jobs.fixtures_attribute_group_access_yml.title
            type:  fixtures
            steps:
                import:
                    title:     pim_installer.jobs.fixtures_attribute_group_access_yml.import.title
                    services:
                        reader:    pim_base_connector.reader.file.yaml
                        processor: pimee_base_connector.processor.attribute_group_access
                        writer:    pim_base_connector.writer.doctrine

        fixtures_category_access_yml:
            title: pim_installer.jobs.fixtures_category_access_yml.title
            type:  fixtures
            steps:
                import:
                    title:     pim_installer.jobs.fixtures_category_access_yml.import.title
                    services:
                        reader:    pim_base_connector.reader.file.yaml
                        processor: pimee_base_connector.processor.category_access
                        writer:    pim_base_connector.writer.doctrine

        fixtures_job_profile_access_yml:
            title: pim_installer.jobs.fixtures_job_profile_yml.title
            type:  fixtures
            steps:
                import:
                    title:     pim_installer.jobs.fixtures_job_profile_access_yml.import.title
                    services:
                        reader:    pim_base_connector.reader.file.yaml
                        processor: pimee_base_connector.processor.job_profile_access
                        writer:    pim_base_connector.writer.doctrine
