parameters:
    pim_installer.fixture_loader.job_loader.config_file:   'PimInstallerBundle/Resources/config/fixtures_jobs.yml'
    pimee_installer.fixture_loader.job_loader.config_file: 'PimEnterpriseInstallerBundle/Resources/config/fixture_jobs.yml'

services:
    pim_installer.fixture_loader.job_loader:
        class: %pim_installer.fixture_loader.job_loader.class%
        arguments:
            - '@service_container'
            - [ %pim_installer.fixture_loader.job_loader.config_file%, %pimee_installer.fixture_loader.job_loader.config_file% ]
