parameters:
    pimee_rule_engine.entity.rule.class: PimEnterprise\Bundle\RuleEngineBundle\Model\Rule
    pimee_rule_engine.entity.loaded_rule.class: PimEnterprise\Bundle\RuleEngineBundle\Model\LoadedRule
    pimee_rule_engine.entity.rule_subject_set.class: PimEnterprise\Bundle\RuleEngineBundle\Model\RuleSubjectSet
