parameters:
    pimee_rule_engine.manager.rule.class: PimEnterprise\Bundle\RuleEngineBundle\Manager\RuleManager

services:
    # Managers
    pimee_rule_engine.manager.rule:
        class: %pimee_rule_engine.manager.rule.class%
        arguments:
            - '@pimee_catalog_rule.repository.rule_linked_resource'
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
