parameters:
    pimee_rule_engine.normalizer.rule_collection.class: PimEnterprise\Bundle\RuleEngineBundle\Normalizer\RuleCollectionNormalizer
    pimee_rule_engine.normalizer.rule_definition.class: PimEnterprise\Bundle\RuleEngineBundle\Normalizer\RuleDefinitionNormalizer

services:
   pimee_rule_engine.normalizer.rule_collection:
        class: %pimee_rule_engine.normalizer.rule_collection.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pimee_rule_engine.normalizer.rule_definition:
        class: %pimee_rule_engine.normalizer.rule_definition.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }
