parameters:
    pimee_rule_engine.repository.rule.class: PimEnterprise\Bundle\RuleEngineBundle\Repository\RuleRepository

services:
    pimee_rule_engine.repository.rule:
        class: %pimee_rule_engine.repository.rule.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pimee_rule_engine.entity.rule.class%]
        tags:
            - { name: 'pim_repository' }
