parameters:
    pimee_rule_engine.repository.rule_definition.class: PimEnterprise\Bundle\RuleEngineBundle\Doctrine\ORM\Repository\RuleDefinitionRepository

services:
    pimee_rule_engine.repository.rule_definition:
        class: %pimee_rule_engine.repository.rule_definition.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pimee_rule_engine.model.rule_definition.class%]
        tags:
            - { name: 'pim_repository' }
