parameters:
    pimee_rule_engine.runner.chained.class: PimEnterprise\Bundle\RuleEngineBundle\Runner\ChainedRunner

services:
    pimee_rule_engine.runner.chained:
        class: %pimee_rule_engine.runner.chained.class%

    pimee_rule_engine.runner.batch:
        abstract: true
        calls:
            - [ setRootDir, [%kernel.root_dir%]]
            - [ setEnvironment, [%kernel.environment%]]
            - [ setJobCode, ['rule_engine']]
