parameters:
    pimee_versioning.denormalizer.product.class: PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductDenormalizer
    pimee_versioning.denormalizer.family.class:  PimEnterprise\Bundle\VersioningBundle\Denormalizer\FamilyDenormalizer

services:
    pimee_versioning.denormalizer.product:
        class: %pimee_versioning.denormalizer.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.product.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.family:
        class: %pimee_versioning.denormalizer.family.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.family.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
