parameters:
    pimee_versioning.denormalizer.product.class:           PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductDenormalizer
    pimee_versioning.denormalizer.family.class:            PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\FamilyDenormalizer
    pimee_versioning.denormalizer.category.class:          PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\CategoryDenormalizer
    pimee_versioning.denormalizer.group.class:             PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\GroupDenormalizer
    pimee_versioning.denormalizer.association.class:       PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\AssociationDenormalizer
    pimee_versioning.denormalizer.product_value.class:     PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValueDenormalizer
    pimee_versioning.denormalizer.base_value.class:        PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\BaseValueDenormalizer
    pimee_versioning.denormalizer.attribute_option.class:  PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\AttributeOptionDenormalizer
    pimee_versioning.denormalizer.attribute_options.class: PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\AttributeOptionsDenormalizer
    pimee_versioning.denormalizer.prices.class:            PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\PricesDenormalizer
    pimee_versioning.denormalizer.metric.class:            PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\MetricDenormalizer
    pimee_versioning.denormalizer.datetime.class:          PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\DateTimeDenormalizer
    pimee_versioning.denormalizer.media.class:             PimEnterprise\Bundle\VersioningBundle\Denormalizer\Flat\ProductValue\MediaDenormalizer

services:
    pimee_versioning.serializer:
        class: %pim_serializer.class%

    pimee_versioning.encoder.csv:
        public: false
        class: %pim_serializer.encoder.csv.class%
        tags:
            - { name: pimee_versioning.serializer.encoder, priority: 90 }

    pimee_versioning.denormalizer.product:
        class: %pimee_versioning.denormalizer.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.product.class%
            - '@pim_catalog.builder.product'
            - '@pim_transform.builder.field_name'
            - %pim_catalog.entity.association.class%
            - %pim_catalog.entity.category.class%
            - %pim_catalog.entity.family.class%
            - %pim_catalog.entity.group.class%
            - %pim_catalog.entity.product_value.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.family:
        class: %pimee_versioning.denormalizer.family.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.family.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.category:
        class: %pimee_versioning.denormalizer.category.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.category.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.group:
        class: %pimee_versioning.denormalizer.group.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.group.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.association:
        class: %pimee_versioning.denormalizer.association.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.association.class%
            - %pim_catalog.entity.association_type.class%
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.group.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.product_value:
        class: %pimee_versioning.denormalizer.product_value.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.product_value.class%
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.base_value:
        class: %pimee_versioning.denormalizer.base_value.class%
        arguments:
            - ['pim_catalog_identifier', 'pim_catalog_text', 'pim_catalog_textarea', 'pim_catalog_number', 'pim_catalog_boolean']
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.attribute_option:
        class: %pimee_versioning.denormalizer.attribute_option.class%
        arguments:
            - ['pim_catalog_simpleselect']
            - '@pim_catalog.repository.attribute_option'
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.attribute_options:
        class: %pimee_versioning.denormalizer.attribute_options.class%
        arguments:
            - ['pim_catalog_multiselect']
            - '@pim_catalog.repository.attribute_option'
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.prices:
        class: %pimee_versioning.denormalizer.prices.class%
        arguments:
            - ['pim_catalog_price_collection']
            - '@pim_catalog.builder.product'
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.metric:
        class: %pimee_versioning.denormalizer.metric.class%
        arguments:
            - ['pim_catalog_metric']
            - '@pim_catalog.factory.metric'
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.datetime:
        class: %pimee_versioning.denormalizer.datetime.class%
        arguments:
            - ['pim_catalog_date']
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.media:
        class: %pimee_versioning.denormalizer.media.class%
        arguments:
            - ['pim_catalog_image', 'pim_catalog_file']
            - '@pim_catalog.manager.media'
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }
