parameters:
    pimee_versioning.denormalizer.product.class:       PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductDenormalizer
    pimee_versioning.denormalizer.family.class:        PimEnterprise\Bundle\VersioningBundle\Denormalizer\FamilyDenormalizer
    pimee_versioning.denormalizer.category.class:      PimEnterprise\Bundle\VersioningBundle\Denormalizer\CategoryDenormalizer
    pimee_versioning.denormalizer.group.class:         PimEnterprise\Bundle\VersioningBundle\Denormalizer\GroupDenormalizer
    pimee_versioning.denormalizer.association.class:   PimEnterprise\Bundle\VersioningBundle\Denormalizer\AssociationDenormalizer
    pimee_versioning.denormalizer.product_value.class: PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductValueDenormalizer
    pimee_versioning.denormalizer.dummy.class:         PimEnterprise\Bundle\VersioningBundle\Denormalizer\DummyDenormalizer
    pimee_versioning.denormalizer.base_value.class:    PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductValue\BaseValueDenormalizer
    pimee_versioning.denormalizer.attribute_option.class: PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductValue\AttributeOptionDenormalizer
    pimee_versioning.denormalizer.attribute_options.class: PimEnterprise\Bundle\VersioningBundle\Denormalizer\ProductValue\AttributeOptionsDenormalizer

services:
    pimee_versioning.denormalizer.product:
        class: %pimee_versioning.denormalizer.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.product.class%
            - '@pim_catalog.builder.product'
            - '@pim_transform.builder.field_name'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.family:
        class: %pimee_versioning.denormalizer.family.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.family.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.category:
        class: %pimee_versioning.denormalizer.category.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.category.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.group:
        class: %pimee_versioning.denormalizer.group.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.group.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.association:
        class: %pimee_versioning.denormalizer.association.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.association.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.product_value:
        class: %pimee_versioning.denormalizer.product_value.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - %pim_catalog.entity.product_value.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.dummy:
        class: %pimee_versioning.denormalizer.dummy.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 30 }

    pimee_versioning.denormalizer.base_value:
        class: %pimee_versioning.denormalizer.base_value.class%
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.attribute_option:
        class: %pimee_versioning.denormalizer.attribute_option.class%
        arguments:
            - '@pim_catalog.repository.attribute_option'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pimee_versioning.denormalizer.attribute_options:
        class: %pimee_versioning.denormalizer.attribute_options.class%
        parent: pimee_versioning.denormalizer.attribute_option
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
