parameters:
    pimee_versioning.reverter.version.class: PimEnterprise\Bundle\VersioningBundle\Reverter\VersionReverter

services:
    pimee_versioning.reverter.version:
        class: %pimee_versioning.reverter.version.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_serializer'
            - '@pim_catalog.manager.product'
