PimEnterprise\Bundle\SecurityBundle\Entity\AttributeGroupAccess:
    type: entity
    table: pimee_security_attribute_group_access
    repositoryClass: PimEnterprise\Bundle\SecurityBundle\Entity\Repository\AttributeGroupAccessRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        viewAttributes:
            type: boolean
            column: view_attributes
            options:
                default: false
        editAttributes:
            type: boolean
            column: edit_attributes
            options:
                default: false
    manyToOne:
        attributeGroup:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeGroup
            joinColumn:
                name: attribute_group_id
                referencedColumnName: id
                nullable: false
        role:
            targetEntity: Oro\Bundle\UserBundle\Entity\Role
            joinColumn:
                name: role_id
                referencedColumnName: id
                nullable: false
