services:

    pimee_transform.transformer.guesser.job_profile_access_job_profile:
        class: %pim_transform.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_transform.transformer.property.relation'
            - %pimee_security.entity.job_profile_access.class%
            - ['/^jobProfile/']
            - { class: %akeneo_batch.entity.job_instance.class% }
        tags:
            - { name: pim_transform.transformer.guesser, priority: 40 }
