parameters:
    pimee_base_connector.processor.attribute_group_access.class: PimEnterprise\Bundle\BaseConnectorBundle\Processor\AttributeGroupAccessProcessor
    pimee_base_connector.processor.category_access.class:        PimEnterprise\Bundle\BaseConnectorBundle\Processor\CategoryAccessProcessor

services:
    pimee_base_connector.processor.attribute_group_access:
        parent: pim_base_connector.processor.transformer
        class: %pimee_base_connector.processor.attribute_group_access.class%
        arguments:
            - %pimee_catalog.entity.attribute_group_access.class%

    pimee_base_connector.processor.category_access:
        parent: pim_base_connector.processor.transformer
        class: %pimee_base_connector.processor.category_access.class%
        arguments:
            - %pimee_security.entity.category_access.class%
