parameters:
    pimee_enrich.view_element.tab.category_permissions.template: 'PimEnterpriseEnrichBundle:CategoryTree:Tab/permissions.html.twig'

services:
    pimee_enrich.view_element.tab.category_permission_base:
        parent: pim_enrich.view_element.tab.base
        arguments:
            - %pimee_enrich.view_element.tab.category_permissions.template%
            - 'tab.pimee_enrich_category_edit.permissions'

    pimee_enrich.view_element.tab.category_permission_on_form_edit:
        parent: pim_enrich.view_element.tab.on_form_edit
        arguments:
            - @pimee_enrich.view_element.tab.category_permission_base

    pimee_enrich.view_element.tab.category_permission:
        parent: pim_enrich.view_element.tab.granted
        arguments:
            - @pimee_enrich.view_element.tab.category_permission_on_form_edit
            - 'pimee_enrich_category_edit_permissions'
        tags:
            - { name: pim_enrich_view_element.tab, position: 100, identifier: pim_enrich_category_edit }
