parameters:
    pimee_enrich.view_element.product.tab.category:  'PimEnterpriseEnrichBundle:Product:Tab/attribute_edit.html.twig'
    pimee_enrich.view_element.product.tab.proposal: 'PimEnterpriseEnrichBundle:Product:Tab/proposal.html.twig'

services:
    # Category
    pim_enrich.view_element.product.tab.category:
        parent: pim_enrich.view_element.base
        arguments:
            - 'product.tab.category'
            - %pimee_enrich.view_element.product.tab.category.template%
        calls:
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_product_categories_view'}] ]
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_product_categories_view'}] ] //TODO
        tags:
            - { name: pim_enrich.view_element, type: pim_product_edit.form_tab, position: 100 }

    # Association
    pim_enrich.view_element.product.tab.association:
        parent: pim_enrich.view_element.base
        arguments:
            - 'product.tab.association'
            - %pim_enrich.view_element.product.tab.association.template%
        calls:
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_associations_view'}] ]
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_associations_view'}] ] //TODO
        tags:
            - { name: pim_enrich.view_element, type: pim_product_edit.form_tab, position: 110 }

    # Proposal
    pim_enrich.view_element.product.tab.proposal:
        parent: pim_enrich.view_element.base
        arguments:
            - 'product.tab.proposal'
            - %pimee_enrich.view_element.product.tab.proposal%
        calls:
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_associations_view'}] ]
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_associations_view'}] ] //TODO
        tags:
            - { name: pim_enrich.view_element, type: pim_product_edit.form_tab, position: 140 }