pimee_enrich_product_show:
    path: /{id}/show
    defaults: { _controller: pim_enrich.controller.product:showAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET]

pimee_enrich_product_dispatch:
    path: /{id}/dispatch
    defaults: { _controller: pim_enrich.controller.product:dispatchAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET]

pimee_enrich_product_value_show:
    path: /{productId}/attribute/{attributeCode}
    defaults: { _controller: pim_enrich.controller.product:showAttributeAction }
    requirements:
        product: '[0-9a-f]+'
    methods: [GET]

pimee_enrich_attribute_rules:
    path: /smart_attribute
    defaults: { _controller: pimee_catalog_rule.controller.rule:listAttributeRulesAction }
    methods: [GET]

pimee_enrich_product_product_drafts:
    path: /{id}/product_drafts
    defaults: { _controller: pim_enrich.controller.product:draftsAction }
    requirements:
        product: '[0-9a-f]+'
    methods: [GET]
