parameters:
    pimee_workflow.controller.product_draft.class: PimEnterprise\Bundle\WorkflowBundle\Controller\PropositionController
    pimee_workflow.controller.published_product.class: PimEnterprise\Bundle\WorkflowBundle\Controller\PublishedProductController

services:
    pimee_workflow.controller.product_draft:
        class: %pimee_workflow.controller.product_draft.class%
        parent: pim_enrich.controller.abstract
        scope: request
        arguments:
            - '@pimee_workflow.repository.product_draft'
            - '@pimee_workflow.manager.product_draft'
            - '@pim_user.context.user'

    pimee_workflow.controller.published_product:
        class: %pimee_workflow.controller.published_product.class%
        parent: pim_enrich.controller.abstract
        scope: request
        arguments:
            - '@pim_user.context.user'
            - '@pimee_workflow.manager.published_product'
            - '@pim_versioning.manager.version'
