datagrid:
    proposals-grid:
        source:
            type: pim_orm
            entity: %pimee_workflow.entity.proposal.class%
            repository_method: createDatagridQueryBuilder
        columns:
            createdBy:
                label: pimee_workflow.proposal.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.proposal.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.proposal.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.proposal.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/proposal_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_proposal_approve
                params:
                    - id
            refuse_link:
                type: url
                route: pimee_workflow_proposal_refuse
                params:
                    - id
        actions:
            approve:
                type: navigate
                label: pimee_workflow.proposal.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.proposal.action.refuse
                icon: remove
                link: refuse_link
        action_configuration: @pimee_workflow.datagrid.proposal_grid_helper->getActionConfigurationClosure
