parameters:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposition.class: PimEnterprise\Bundle\WorkflowBundle\Datagrid\EventListener\InjectProductForPropositionSubscriber

services:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposition:
        class: %pimee_workflow.datagrid.event_listener.inject_product_for_proposition.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.proposition-grid, method: buildBefore }

    pim_enrich.event_listener.product_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_product_grid_listener.class%
        arguments:
            - '@pim_datagrid.datagrid.product.context_configurator'
            - '@pim_datagrid.datagrid.product.columns_configurator'
            - '@pim_datagrid.datagrid.product.filters_configurator'
            - '@pim_datagrid.datagrid.product.sorters_configurator'
            - '@pimee_datagrid.datagrid.product.row_actions_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.product-grid, method: buildBefore }

    pim_enrich.event_listener.published_product_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_product_grid_listener.class%
        arguments:
            - '@pim_datagrid.datagrid.product.context_configurator'
            - '@pim_datagrid.datagrid.product.columns_configurator'
            - '@pim_datagrid.datagrid.product.filters_configurator'
            - '@pim_datagrid.datagrid.product.sorters_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.published-product-grid, method: buildBefore }

    pim_enrich.event_listener.published_product_grid_after_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_product_grid.class%
        arguments:
          - [dataLocale]
          - '@oro_datagrid.datagrid.request_params'
          - '@pim_catalog.context.catalog'
          - '@pim_user.context.user'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.published-product-grid, method: onBuildAfter }
        calls:
            - [setRequest, ['@?request=']]
