parameters:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposal.class: PimEnterprise\Bundle\WorkflowBundle\Datagrid\EventListener\InjectProductForProposalSubscriber

services:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposal:
        class: %pimee_workflow.datagrid.event_listener.inject_product_for_proposal.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.proposals-grid, method: buildBefore }

    pim_enrich.event_listener.publishedproduct_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_product_grid_listener.class%
        arguments:
            - '@pim_datagrid.datagrid.product.context_configurator'
            - '@pim_datagrid.datagrid.product.columns_configurator'
            - '@pim_datagrid.datagrid.product.filters_configurator'
            - '@pim_datagrid.datagrid.product.sorters_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.publishedproduct-grid, method: buildBefore }

    pim_enrich.event_listener.publishedproduct_grid_after_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_product_grid.class%
        arguments:
          - [dataLocale]
          - '@oro_datagrid.datagrid.request_params'
          - '@pim_catalog.context.catalog'
          - '@pim_user.context.user'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.publishedproduct-grid, method: onBuildAfter }
