datagrid:
    propositions-grid:
        options:
            entityHint: proposition
        source:
            type: pim_proposition
            entity: %pimee_workflow.model.proposition.class%
            repository_method: createDatagridQueryBuilder
        columns:
            author:
                label: pimee_workflow.proposition.author
                type: field
                frontend_type: string
            locale:
                label: pimee_workflow.proposition.locale
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/locale_flag.html.twig
                frontend_type: html
            changes:
                label: pimee_workflow.proposition.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.proposition.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.proposition.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/proposition_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_proposition_approve
                params:
                    - id
            refuse_link:
                type: url
                route: pimee_workflow_proposition_refuse
                params:
                    - id
        actions:
            approve:
                type: navigate
                label: pimee_workflow.proposition.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.proposition.action.refuse
                icon: remove
                link: refuse_link
        action_configuration: '@pimee_workflow.datagrid.proposition_grid_helper->getActionConfigurationClosure'
        filters:
            columns:
                status:
                    type:        proposition_choice
                    parent_type: choice
                    data_name:   status
                    label:       pimee_workflow.proposition.status.label
                    options:
                        field_options:
                            multiple: true
                            choices: '@pimee_workflow.datagrid.proposition_grid_helper->getStatusChoices'
                locale_context:
                    type:        proposition_choice
                    parent_type: choice
                    data_name:   locale
                    label:       pimee_workflow.proposition.locale
                    options:
                        field_options:
                            multiple: true
                            choices: '@pim_catalog.helper.locale->getActivatedLocaleChoices'
        sorters:
            columns:
                author:
                    data_name: author
                    sorter: proposition_field
                status:
                    data_name: status
                    sorter: proposition_field
                createdAt:
                    data_name: createdAt
                    sorter: proposition_field
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
