datagrid:
    proposals-grid:
        options:
            entityHint: proposal
        source:
            type: pim_proposal
            entity: %pimee_workflow.entity.proposal.class%
            repository_method: createDatagridQueryBuilder
        columns:
            author:
                label: pimee_workflow.proposal.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.proposal.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.proposal.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.proposal.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/proposal_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_proposal_approve
                params:
                    - id
            refuse_link:
                type: url
                route: pimee_workflow_proposal_refuse
                params:
                    - id
        actions:
            approve:
                type: navigate
                label: pimee_workflow.proposal.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.proposal.action.refuse
                icon: remove
                link: refuse_link
        action_configuration: '@pimee_workflow.datagrid.proposal_grid_helper->getActionConfigurationClosure'
        filters:
            columns:
                status:
                    type:        proposal_choice
                    parent_type: choice
                    data_name:   status
                    label:       pimee_workflow.proposal.status.label
                    options:
                        field_options:
                            multiple: true
                            choices: '@pimee_workflow.datagrid.proposal_grid_helper->getStatusChoices'
                locale_context:
                    type:        proposal_choice
                    parent_type: choice
                    data_name:   locale
                    label:       Locale context
                    options:
                        field_options:
                            multiple: true
                            choices: '@pim_catalog.helper.locale->getActivatedLocaleChoices'
        sorters:
            columns:
                author:
                    data_name: author
                    sorter: proposal_field
                status:
                    data_name: status
                    sorter: proposal_field
                createdAt:
                    data_name: createdAt
                    sorter: proposal_field
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
