datagrid:
    propositions-grid:
        options:
            entityHint: proposition
        source:
            type: pim_proposition
            entity: %pimee_workflow.model.proposition.class%
            repository_method: createDatagridQueryBuilder
        columns:
            author:
                label: pimee_workflow.proposition.author
                type: field
                frontend_type: string
            changes:
                label: pimee_workflow.proposition.changes
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: pimee_workflow.proposition.created
                type: field
                frontend_type: datetime
            status:
                label: pimee_workflow.proposition.status.label
                type: twig
                template: PimEnterpriseWorkflowBundle:Datagrid:Property/proposition_status.html.twig
                frontend_type: html
        properties:
            id: ~
            approve_link:
                type: url
                route: pimee_workflow_proposition_approve
                params:
                    - id
            refuse_link:
                type: url
                route: pimee_workflow_proposition_refuse
                params:
                    - id
        actions:
            approve:
                type: navigate
                label: pimee_workflow.proposition.action.approve
                icon: ok
                link: approve_link
            refuse:
                type: navigate
                label: pimee_workflow.proposition.action.refuse
                icon: remove
                link: refuse_link
        action_configuration: '@pimee_workflow.datagrid.proposition_grid_helper->getActionConfigurationClosure'
        filters:
            columns:
                status:
                    type:        proposition_choice
                    parent_type: choice
                    data_name:   status
                    label:       pimee_workflow.proposition.status.label
                    options:
                        field_options:
                            multiple: true
                            choices: '@pimee_workflow.datagrid.proposition_grid_helper->getStatusChoices'
        sorters:
            columns:
                author:
                    data_name: author
                    sorter: proposition_field
                status:
                    data_name: status
                    sorter: proposition_field
                createdAt:
                    data_name: createdAt
                    sorter: proposition_field
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    publishedproduct-grid:
        options:
            entityHint: product
            requireJSModules:
                - pim/datagrid/configure-columns-action
        source:
            acl_resource:      pim_enrich_product_index
            type:              pim_product
            entity:            %pimee_workflow.entity.published_product.class%
            repository_method: createDatagridQueryBuilder
        columns:
            label:
                label:         Label
                data_name:     productLabel
                selector:      product_label
            family:
                label:         Family
                data_name:     familyLabel
                selector:      product_family
            enabled:
                label:         Status
                type:          twig
                template:      PimDataGridBundle:Property:enabled.html.twig
                frontend_type: html
            completeness:
                label:         Complete
                type:          twig
                data_name:     ratio
                template:      PimDataGridBundle:Property:completeness.html.twig
                frontend_type: html
                selector:      product_completeness
            created:
                label:         Created At
                frontend_type: date
            updated:
                label:         Updated At
                frontend_type: date
            groups:
                label:         Groups
                type:          product_groups
                selector:      product_groups
        properties:
            id: ~
            view_link:
                type: url
                route: pimee_workflow_published_product_view
                params:
                    - id
        actions:
            view:
                type:      navigate
                label:     View the product
                icon:      eye-open
                link:      view_link
                rowAction: true
        sorters:
            columns:
                family:
                    data_name: familyLabel
                    sorter:    product_family
                enabled:
                    data_name: enabled
                    sorter:    product_field
                completeness:
                    data_name: ratio
                    sorter:    product_completeness
                created:
                    data_name: created
                    sorter:    product_field
                updated:
                    data_name: updated
                    sorter:    product_field
            default:
                updated: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                family:
                    type:      product_family
                    label:     Family
                    data_name: family
                    options:
                        field_options:
                            attr:
                                empty_choice: true
                            multiple: true
                            choices:  '@pim_catalog.manager.family->getChoices'
                groups:
                    type:      product_groups
                    label:     Groups
                    data_name: groups
                    options:
                        field_options:
                            multiple: true
                            choices: '@pim_catalog.manager.group->getChoices'
                enabled:
                    type:        product_enabled
                    parent_type: choice
                    label:       Status
                    data_name:   enabled
                    options:
                        field_options:
                            choices:
                                1: Enabled
                                0: Disabled
                scope:
                    type:      product_scope
                    label:     Scope
                    data_name: values.scope
                    options:
                        field_options:
                            choices: '@pim_catalog.manager.channel->getChannelChoices'
                category:
                    type:      published_product_category
                    label:     Category
                    data_name: category
                completeness:
                    type:      product_completeness
                    label:     Complete
                    data_name: ratio
                created:
                    type:        product_date
                    parent_type: date
                    data_name:   created
                    label:       Created At
                updated:
                    type:        product_date
                    parent_type: date
                    data_name:   updated
                    label:       Updated At
