parameters:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposition.class: PimEnterprise\Bundle\WorkflowBundle\Datagrid\EventListener\InjectProductForPropositionSubscriber

services:
    pimee_workflow.datagrid.event_listener.inject_product_for_proposition:
        class: %pimee_workflow.datagrid.event_listener.inject_product_for_proposition.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.propositions-grid, method: buildBefore }
