parameters:
    pimee_workflow.factory.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Factory\PropositionFactory

services:
    pimee_workflow.factory.proposition:
        class: %pimee_workflow.factory.proposition.class%
