parameters:
    pimee_workflow.factory.product_draft.class: PimEnterprise\Bundle\WorkflowBundle\Factory\PropositionFactory

services:
    pimee_workflow.factory.product_draft:
        class: %pimee_workflow.factory.product_draft.class%
