parameters:
    pimee_workflow.form.subscriber.collect_product_value_changes.class: PimEnterprise\Bundle\WorkflowBundle\Form\Subscriber\CollectProductValuesSubscriber
    pimee_workflow.form.subscriber.unmap_product_values.class: PimEnterprise\Bundle\WorkflowBundle\Form\Subscriber\UnmapProductValuesSubscriber

services:
    pimee_workflow.form.subscriber.collect_product_value_changes:
        public: false
        class: %pimee_workflow.form.subscriber.collect_product_value_changes.class%
        arguments:
            - '@pimee_workflow.collector.product_submitted_changes'
            - '@pim_catalog.manager.media'
            - '@pim_catalog.factory.media'

    pim_enrich.form.type.edit_common_attributes:
        class: %pim_enrich.form.type.edit_common_attributes.class%
        arguments:
            - '@pim_enrich.form.type.product.view'
            - '@pim_catalog.helper.locale'
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: form.type, alias: pim_enrich_mass_edit_common_attributes }

    pimee_workflow.form.subscriber.unmap_product_values:
        public: false
        class: %pimee_workflow.form.subscriber.unmap_product_values.class%
        arguments:
            - '@security.context'
