oro_menu_config:
    items:
        pimee_workflow_published_product:
            label: pim_menu.item.published_product
            route: pimee_workflow_published_product_index
            aclResourceId: pimee_workflow_published_product_index
            extras:
                routes: ['/^pimee_workflow_published_product_\w+$/']
                position: 15
    tree:
        application_menu:
            children:
                pim_enrich_tab:
                    children:
                        pimee_workflow_published_product: ~

oro_titles:
    pimee_workflow_published_product_index: pim_title.published_product.index
    pimee_workflow_published_product_view:  pim_title.published_product.view
    pimee_enrich_product_dispatch:          pim_title.product.dispatch
    pimee_enrich_product_show:              pim_title.product.show
