oro_menu_config:
    items:
        pimee_workflow_publishedproduct:
            label: pim_menu.item.publishedproduct
            route: pimee_workflow_publishedproduct_index
            aclResourceId: pimee_workflow_publishedproduct_index
            extras:
                routes: ['/^pimee_workflow_publishedproduct_\w+$/']
                position: 15
    tree:
        application_menu:
            children:
                pim_enrich_tab:
                    children:
                        pimee_workflow_publishedproduct: ~

oro_titles:
    pimee_workflow_publishedproduct_index: pim_title.publishedproduct.index
