oro_menu_config:
    items:
        pimee_activity_tab:
            label: pimee_menu.tab.activity
            uri: '#'
            extras:
                position: 40
            showNonAuthorized: false
        pimee_workflow_published_product:
            label: pimee_menu.item.published_product
            route: pimee_workflow_published_product_index
            aclResourceId: pimee_workflow_published_product_index
            extras:
                routes: ['/^pimee_workflow_published_product_\w+$/']
                position: 15
        pimee_workflow_product_draft:
            label: pimee_menu.item.product_draft
            route: pimee_workflow_product_draft_index
            aclResourceId: OWN_AT_LEAST_ONE_CATEGORY
            extras:
                routes: ['/^pimee_workflow_product_draft_\w+$/']
                position: 10
    tree:
        application_menu:
            children:
                pim_enrich_tab:
                    children:
                        pimee_workflow_published_product: ~
                pimee_activity_tab:
                    children:
                        pimee_workflow_product_draft: ~

oro_titles:
    pimee_workflow_published_product_index: pimee_title.published_product.index
    pimee_workflow_published_product_view:  pimee_title.published_product.view
    pimee_enrich_product_dispatch:          pimee_title.product.dispatch
    pimee_enrich_product_show:              pimee_title.product.show
    pimee_workflow_product_draft_index:     pimee_title.product_draft.index
