parameters:
    pim_catalog.persister.product.class: PimEnterprise\Bundle\WorkflowBundle\Persistence\ProductDraftPersister

services:
    pim_catalog.persister.product:
        class: %pim_catalog.persister.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_catalog.manager.completeness'
            - '@security.context'
            - '@pimee_workflow.factory.product_draft'
            - '@pimee_workflow.repository.product_draft'
            - '@event_dispatcher'
            - '@pimee_workflow.collector.product_submitted_changes'
            - '@pimee_workflow.change_set_computer'
