parameters:
    pimee_workflow.applier.product_draft_changes_applier.class: PimEnterprise\Bundle\WorkflowBundle\Form\Applier\ProductDraftChangesApplier
    pimee_workflow.collector.product_submitted_changes.class: PimEnterprise\Bundle\WorkflowBundle\Proposition\ChangesCollector
    pimee_workflow.change_set_computer.class: PimEnterprise\Bundle\WorkflowBundle\Proposition\ChangeSetComputer

services:
    pimee_workflow.applier.product_draft_changes_applier:
        public: false
        class: %pimee_workflow.applier.product_draft_changes_applier.class%
        arguments:
            - '@form.factory'
            - '@event_dispatcher'


    pimee_workflow.collector.product_submitted_changes:
        class: %pimee_workflow.collector.product_submitted_changes.class%

    pimee_workflow.change_set_computer:
        class: %pimee_workflow.change_set_computer.class%
        arguments:
            - '@pimee_workflow.comparator.chained'
            - '@event_dispatcher'
            - '@pim_catalog.builder.product'
