parameters:
    pimee_workflow.applier.proposition_changes_applier.class: PimEnterprise\Bundle\WorkflowBundle\Form\Applier\PropositionChangesApplier
    pimee_workflow.collector.product_submitted_changes.class: PimEnterprise\Bundle\WorkflowBundle\Proposition\ChangesCollector
    pimee_workflow.change_set_computer.class: PimEnterprise\Bundle\WorkflowBundle\Proposition\ChangeSetComputer
    pimee_workflow.form.type.product.highlight_modified_values_view.class: PimEnterprise\Bundle\WorkflowBundle\Form\View\HighlightModifiedProductFormView

services:
    pimee_workflow.applier.proposition_changes_applier:
        public: false
        class: %pimee_workflow.applier.proposition_changes_applier.class%
        arguments:
            - '@form.factory'
            - '@event_dispatcher'

    ##
    # Product form view decorator
    ##
    pimee_workflow.form.type.product.highlight_modified_values_view:
        class: %pimee_workflow.form.type.product.highlight_modified_values_view.class%
        arguments:
            - '@pim_enrich.form.type.product.view'
            - '@pimee_workflow.applier.proposition_changes_applier'
            - '@router'

    ##
    # Product form view overriding
    ##
    pim_enrich.form.type.product_value:
        class: %pim_enrich.form.type.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%
            - '@pim_enrich.form.subscriber.add_value_field_subscriber'
            - '@pimee_workflow.form.type.product.highlight_modified_values_view'
        tags:
            - { name: form.type, alias: pim_product_value }

    pimee_workflow.collector.product_submitted_changes:
        class: %pimee_workflow.collector.product_submitted_changes.class%

    pimee_workflow.change_set_computer:
        class: %pimee_workflow.change_set_computer.class%
        arguments:
            - '@pimee_workflow.comparator.chained'
            - '@event_dispatcher'
            - '@pim_catalog.builder.product'
