parameters:
    pimee_workflow.factory.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Factory\PropositionFactory
    pimee_workflow.manager.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Manager\PropositionManager
    pimee_workflow.applier.proposition_changes_applier.class: PimEnterprise\Bundle\WorkflowBundle\Form\Applier\PropositionChangesApplier
    pimee_workflow.product_changes_applier.prepare_uploading_media.class: PimEnterprise\Bundle\WorkflowBundle\EventSubscriber\Proposition\PrepareUploadingMediaSubscriber
    pimee_workflow.product_changes_applier.submit_proposition_form.class: PimEnterprise\Bundle\WorkflowBundle\EventSubscriber\Proposition\SubmitPropositionFormSubscriber
    pimee_workflow.subscriber.inject_current_user_proposition.class: PimEnterprise\Bundle\WorkflowBundle\EventSubscriber\Enrich\InjectCurrentUserPropositionSubscriber
    pimee_workflow.subscriber.add_proposition_form_view_parameter.class: PimEnterprise\Bundle\WorkflowBundle\EventSubscriber\Enrich\AddPropositionFormViewParameterSubscriber
    pimee_workflow.form.type.product.highlight_modified_values_view.class: PimEnterprise\Bundle\WorkflowBundle\Form\View\HighlightModifiedProductFormView

services:
    pimee_workflow.factory.proposition:
        class: %pimee_workflow.factory.proposition.class%

    pimee_workflow.manager.proposition:
        class: %pimee_workflow.manager.proposition.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_catalog.manager.product'
            - '@pimee_workflow.applier.proposition_changes_applier'

    pimee_workflow.applier.proposition_changes_applier:
        public: false
        class: %pimee_workflow.applier.proposition_changes_applier.class%
        arguments:
            - '@form.factory'
            - '@event_dispatcher'

    ##
    # Preparators of product changes before applying
    ##
    pimee_workflow.product_changes_applier.prepare_uploading_media:
        class: %pimee_workflow.product_changes_applier.prepare_uploading_media.class%
        tags:
            - { name: kernel.event_subscriber }

    ##
    # Product form view decorator
    ##
    pimee_workflow.form.type.product.highlight_modified_values_view:
        class: %pimee_workflow.form.type.product.highlight_modified_values_view.class%
        arguments:
            - '@pim_enrich.form.type.product.view'
            - '@pimee_workflow.applier.proposition_changes_applier'

    ##
    # Product form view overriding
    ##
    pim_enrich.form.type.product_value:
        class: %pim_enrich.form.type.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%
            - '@pim_enrich.form.subscriber.add_value_field_subscriber'
            - '@pimee_workflow.form.type.product.highlight_modified_values_view'
        tags:
            - { name: form.type, alias: pim_product_value }

    ##
    # Product to edit preparation
    ##
    pimee_workflow.subscriber.inject_current_user_proposition:
        class: %pimee_workflow.subscriber.inject_current_user_proposition.class%
        arguments:
            - '@pim_user.context.user'
            - '@pim_catalog.context.catalog'
            - '@pimee_workflow.repository.proposition'
            - '@pimee_workflow.applier.proposition_changes_applier'
        tags:
            - { name: kernel.event_subscriber }
