parameters:
    pimee_workflow.publisher.product.class:         PimEnterprise\Bundle\WorkflowBundle\Publisher\ProductPublisher
    pimee_workflow.factory.published_product.class: PimEnterprise\Bundle\WorkflowBundle\Factory\PublishedProductFactory

services:
    pimee_workflow.publisher.product:
        class: %pimee_workflow.publisher.product.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - '@pimee_workflow.repository.published_product'
            - '@pimee_workflow.factory.published_product'

    pimee_workflow.factory.published_product:
        class: %pimee_workflow.factory.published_product.class%
        arguments:
            - '@pimee_workflow.repository.published_product'
