parameters:
    pimee_workflow.manager.published_product.class: PimEnterprise\Bundle\WorkflowBundle\Manager\PublishedProductManager

services:

    pimee_workflow.manager.published_product:
        class: %pimee_workflow.manager.published_product.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@pimee_workflow.repository.published_product'
            - '@event_dispatcher'
            - '@pimee_workflow.publisher.chained'
            - '@pimee_workflow.unpublisher.product'

    pimee_workflow.manager.published_product_category:
        class: %pim_catalog.manager.product_category.class%
        arguments:
            - '@pimee_workflow.repository.published_product_category'
            - '@pim_catalog.repository.category'
            - '@security.context'
            - '@pimee_security.repository.category_access'
