services:
    pimee_workflow.repository.published_product_mass_action:
        class: %pim_catalog.repository.product_mass_action.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - %pimee_workflow.entity.published_product.class%
            - '@pimee_workflow.repository.published_product'
