services:
    pimee_workflow.repository.proposition:
        class: %pimee_workflow.repository.proposition.class%
        factory_service: pimee_workflow.object_manager.proposition
        factory_method: getRepository
        arguments: [%pimee_workflow.model.proposition.class%]
