proposal:
    resource: '@PimEnterpriseWorkflowBundle/Resources/config/routing/proposal.yml'
    prefix: /proposal
publishedproduct:
    resource: '@PimEnterpriseWorkflowBundle/Resources/config/routing/publishedproduct.yml'
    prefix: /workflow/published-product
