proposition:
    resource: '@PimEnterpriseWorkflowBundle/Resources/config/routing/proposition.yml'
    prefix: /proposition
published_product:
    resource: '@PimEnterpriseWorkflowBundle/Resources/config/routing/published_product.yml'
    prefix: /workflow/published-product
