parameters:
    pim_catalog.saver.product.class: PimEnterprise\Bundle\WorkflowBundle\Saver\ProductDraftSaver

services:
    pim_catalog.saver.product:
        class: %pim_catalog.saver.product.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - '@pim_catalog.manager.completeness'
            - '@security.context'
            - '@pimee_workflow.factory.product_draft'
            - '@pimee_workflow.repository.product_draft'
            - '@event_dispatcher'
            - '@pimee_workflow.collector.product_submitted_changes'
            - '@pimee_workflow.change_set_computer'
            - %pim_catalog.storage_driver%
            - '@pimee_rule_engine.repository.rule'
            - '@pimee_catalog_rule.runner.product'
