parameters:
    pimee_workflow.saver.product_draft.class:      PimEnterprise\Bundle\WorkflowBundle\Saver\ProductDraftSaver
    pimee_workflow.saver.product_delegating.class: PimEnterprise\Bundle\WorkflowBundle\Saver\DelegatingProductSaver

services:
    # product working copy saver, we alias the product saver from community edition to make the behavior more explicit
    pimee_workflow.saver.working_copy_product:
        alias: pim_catalog.saver.product

    # product draft saver
    pimee_workflow.saver.product_draft:
        class: %pimee_workflow.saver.product_draft.class%
        arguments:
            - @pim_catalog.object_manager.product
            - @security.context
            - @pimee_workflow.factory.product_draft
            - @pimee_workflow.repository.product_draft
            - @event_dispatcher
            - @pimee_workflow.collector.product_submitted_changes
            - @pimee_workflow.change_set_computer
            - %akeneo_storage_utils.storage_driver%

    # this product saver delegates to draft or working copy savers depending on user permissions
    # TODO : would avoid this if possible, only used for mass edit which could embed this behavior ?
    # TODO : what about proposal on non existing product ?
    # TODO : it now works with mass edit but not anymore with product saving, some controller / handler refactoring to do
    pimee_workflow.saver.product_delegating:
        class: %pimee_workflow.saver.product_delegating.class%
        arguments:
            - @pimee_workflow.saver.working_copy_product
            - @pimee_workflow.saver.product_draft
            - @pim_catalog.object_manager.product # TODO not very used, should check
            - @security.context

    # TODO : add a saver for published product