parameters:
    pimee_workflow.normalizer.product.class: PimEnterprise\Bundle\WorkflowBundle\Serializer\ProductNormalizer
    pimee_workflow.normalizer.product_value.class: PimEnterprise\Bundle\WorkflowBundle\Serializer\ProductValueNormalizer
    pimee_workflow.normalizer.media.class: PimEnterprise\Bundle\WorkflowBundle\Serializer\MediaNormalizer
    pimee_workflow.normalizer.prices_collection.class: PimEnterprise\Bundle\WorkflowBundle\Serializer\PricesCollectionNormalizer


services:
    pimee_workflow.normalizer.product:
        public: false
        class: %pimee_workflow.normalizer.product.class%
        tags:
            - { name: pim_serializer.normalizer }

    pimee_workflow.normalizer.product_value:
        public: false
        class: %pimee_workflow.normalizer.product_value.class%
        tags:
            - { name: pim_serializer.normalizer }

    pimee_workflow.normalizer.media:
        public: false
        class: %pimee_workflow.normalizer.media.class%
        tags:
            - { name: pim_serializer.normalizer }

    pimee_workflow.normalizer.prices_collection:
        public: false
        class: %pimee_workflow.normalizer.prices_collection.class%
        tags:
            - { name: pim_serializer.normalizer }

    pimee_workflow.normalizer.dummy:
        public: false
        class: PimEnterprise\Bundle\WorkflowBundle\Serializer\DummyNormalizer
        tags:
            - { name: pim_serializer.normalizer }
