parameters:
    pimee_workflow.model.proposition.class: PimEnterprise\Bundle\WorkflowBundle\Model\Proposition
    pimee_workflow.datagrid.proposition_grid_helper.class: PimEnterprise\Bundle\WorkflowBundle\Datagrid\PropositionGridHelper

services:
    pimee_workflow.event_listener.propositions_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [ product ]
          - '@oro_datagrid.datagrid.request_params'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.proposition-grid, method: onBuildAfter }

    pimee_workflow.datagrid.proposition_grid_helper:
        class: %pimee_workflow.datagrid.proposition_grid_helper.class%
