datagrid:
    proposals-grid:
        source:
            type: pim_orm
            entity: %pimee_catalog.entity.proposal.class%
            repository_method: createDatagridQueryBuilder
        columns:
            createdBy:
                label: Proposed by
                type: field
                frontend_type: string
            changes:
                label: Changes
                type: twig
                template: PimEnterpriseEnrichBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: Proposed at
                type: field
                frontend_type: datetime
