parameters:
    pimee_datagrid.event_listener.configure_product_draft_grid_listener.class: PimEnterprise\Bundle\DataGridBundle\EventListener\ConfigureProductDraftGridListener

services:
    pimee_enrich.event_listener.product_draft_grid_before_listener:
        class: %pimee_datagrid.event_listener.configure_product_draft_grid_listener.class%
        arguments:
            - '@pimee_datagrid.datagrid.product_draft.context_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.draft-grid, method: buildBefore }
