parameters:
    pimee_enrich.event_listener.attribute_option.class: PimEnterprise\Bundle\EnrichBundle\EventListener\AttributeOptionEventListener

services:
    pimee_enrich.event_listener.attribute_option:
        class: %pimee_enrich.event_listener.attribute_option.class%
        arguments:
            - '@pimee_workflow.repository.published_product'
        tags:
            - { name: kernel.event_listener, event: pim_catalog.pre_remove.attribute_option, method: onAttributeOptionDelete }
