parameters:
    pimee_enrich.form.type.attribute_group_permissions.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\AttributeGroupPermissionsType
    pimee_enrich.form.type.category_permissions.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\CategoryPermissionsType
    pimee_enrich.form.type.locale_permissions.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\LocalePermissionsType
    pim_enrich.form.type.available_attributes.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\AvailableAttributesType
    pim_enrich.form.type.edit_common_attributes.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\MassEditAction\EditCommonAttributesType
    pimee_enrich.form.type.publish.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\MassEditAction\PublishType
    pimee_enrich.form.type.unpublish.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\MassEditAction\UnpublishType
    pimee_enrich.form.type.classify.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\MassEditAction\ClassifyType
    pimee_enrich.form.type.locale.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\LocaleType

services:
    ##
    # Product form view overriding
    ##
    pim_enrich.form.type.product_value:
        class: %pim_enrich.form.type.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%
            - '@pim_enrich.form.subscriber.add_value_field_subscriber'
            - '@pimee_workflow.form.type.product.highlight_modified_values_view'
        tags:
            - { name: form.type, alias: pim_product_value }

    pim_enrich.form.type.product_edit:
        class: %pim_enrich.form.type.product_edit.class%
        arguments:
            - '@pimee_workflow.form.type.product.highlight_modified_values_view'
            - '@pim_catalog.repository.family'
            - '%pim_catalog.entity.category.class%'
        tags:
            - { name: form.type, alias: pim_product_edit }
        calls:
            - [addEventSubscriber, ['@pimee_security.form.subscriber.remove_product_value_subscriber']]
            - [addEventSubscriber, ['@pimee_workflow.form.subscriber.collect_product_value_changes']]

    pim_enrich.form.type.attribute_group:
        class: %pim_enrich.form.type.attribute_group.class%
        tags:
            - { name: form.type, alias: pim_enrich_attribute_group }
        calls:
            - [addEventSubscriber, ['@pimee_enrich.form.subscriber.attribute_group_permissions']]

    pim_enrich.form.type.product.view:
        public: false
        class: %pim_enrich.form.type.product.view.class%
        arguments:
            - '@security.context'

    pim_enrich.form.type.available_attributes:
        class: %pim_enrich.form.type.available_attributes.class%
        arguments:
            - %pim_catalog.entity.attribute.class%
            - '@pim_catalog.repository.attribute'
            - '@pim_user.context.user'
            - '@translator'
            - '@pimee_security.repository.attribute_group_access'
        tags:
            - { name: form.type, alias: pim_available_attributes }

    pim_enrich.form.type.category:
        class: %pim_enrich.form.type.category.class%
        arguments:
            - %pim_catalog.entity.category.class%
            - %pim_catalog.entity.category_translation.class%
        tags:
            - { name: form.type, alias: pim_category }
        calls:
            - [addEventSubscriber, ['@pimee_enrich.form.subscriber.category_permissions']]

    pim_enrich.form.type.edit_common_attributes:
        class: %pim_enrich.form.type.edit_common_attributes.class%
        arguments:
            - '@pim_enrich.form.type.product.view'
            - '@pim_catalog.helper.locale'
            - %pim_catalog.entity.attribute.class%
            - '@pimee_workflow.form.subscriber.collect_product_mass_edit_value_changes'
        tags:
            - { name: form.type, alias: pim_enrich_mass_edit_common_attributes }

    ##
    # New forms
    ##
    pimee_enrich.form.type.attribute_group_permissions:
        class: %pimee_enrich.form.type.attribute_group_permissions.class%
        tags:
            - { name: form.type, alias: pimee_enrich_attribute_group_permissions }

    pimee_enrich.form.type.category_permissions:
        class: %pimee_enrich.form.type.category_permissions.class%
        tags:
            - { name: form.type, alias: pimee_enrich_category_permissions }

    pimee_enrich.form.type.publish:
        class: %pimee_enrich.form.type.publish.class%
        tags:
            - { name: form.type, alias: pimee_enrich_mass_publish }

    pimee_enrich.form.type.unpublish:
        class: %pimee_enrich.form.type.unpublish.class%
        tags:
            - { name: form.type, alias: pimee_enrich_mass_unpublish }

    pimee_enrich.form.type.classify:
        class: %pimee_enrich.form.type.classify.class%
        tags:
            - { name: form.type, alias: pimee_enrich_mass_classify }

    pimee_enrich.form.type.locale:
        class: %pimee_enrich.form.type.locale.class%
        tags:
            - { name: form.type, alias: pimee_enrich_locale }
        calls:
            - [addEventSubscriber, ['@pimee_enrich.form.subscriber.locale_permissions']]

    pimee_enrich.form.type.locale_permissions:
        class: %pimee_enrich.form.type.locale_permissions.class%
        tags:
            - { name: form.type, alias: pimee_enrich_locale_permissions }
