parameters:
    pimee_enrich.form.type.attribute_group_rights.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\AttributeGroupRightsType
    pim_enrich.form.type.available_attributes.class:     PimEnterprise\Bundle\EnrichBundle\Form\Type\AvailableAttributesType

services:
    pim_enrich.form.type.product_edit:
        class: %pim_enrich.form.type.product_edit.class%
        arguments:
            - '@pim_enrich.form.type.product.view'
            - '@pim_catalog.repository.family'
            - '%pim_catalog.entity.category.class%'
        tags:
            - { name: form.type, alias: pim_product_edit }
        calls:
            - [addEventSubscriber, ['@pimee_security.form.subscriber.remove_product_value_subscriber']]

    pim_enrich.form.type.attribute_group:
        class: %pim_enrich.form.type.attribute_group.class%
        tags:
            - { name: form.type, alias: pim_enrich_attribute_group }
        calls:
            - [addEventSubscriber, ['@pimee_enrich.form.subscriber.attribute_group_rights']]

    pimee_enrich.form.type.attribute_group_rights:
        class: %pimee_enrich.form.type.attribute_group_rights.class%
        tags:
            - { name: form.type, alias: pimee_enrich_attribute_group_rights }

    pim_enrich.form.type.product.view:
        public: false
        class: %pim_enrich.form.type.product.view.class%
        arguments:
            - '@security.context'

    pim_enrich.form.type.available_attributes:
        class: %pim_enrich.form.type.available_attributes.class%
        arguments:
            - %pim_catalog.entity.attribute.class%
            - '@pim_catalog.repository.attribute'
            - '@pim_user.context.user'
            - '@translator'
            - '@pimee_security.repository.attribute_group_access'
        tags:
            - { name: form.type, alias: pim_available_attributes }
