parameters:
    pim_enrich.form.handler.attribute.class: PimEnterprise\Bundle\EnrichBundle\Form\Handler\AttributeHandler

services:
    pim_enrich.form.handler.attribute:
        class: %pim_enrich.form.handler.attribute.class%
        scope: request
        arguments:
            - '@pim_enrich.form.attribute'
            - '@request'
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.manager.attribute'
            - '@pimee_workflow.repository.published_product'
