parameters:
    pim_enrich.mass_edit_action.classify.class: PimEnterprise\Bundle\EnrichBundle\MassEditAction\Operation\Classify
    pimee_enrich.mass_edit_action.publish.class: PimEnterprise\Bundle\EnrichBundle\MassEditAction\Operation\Publish

services:
    pim_enrich.mass_edit_action.classify:
        public: false
        class: %pim_enrich.mass_edit_action.classify.class%
        arguments:
            - '@pim_catalog.manager.category'
            - '@security.context'
        tags:
            -
                name: pim_enrich.mass_edit_action
                alias: classify
                acl: pim_enrich_product_categories_view
                operator: pim_enrich.mass_edit_action.operator.product

    pimee_enrich.mass_edit_action.publish:
        public: false
        class: %pimee_enrich.mass_edit_action.publish.class%
        arguments:
            - '@pimee_workflow.manager.published_product'
            - '@security.context'
        tags:
            -
                name: pim_enrich.mass_edit_action
                alias: publish
                acl: pimee_workflow_published_product_publish
                operator: pim_enrich.mass_edit_action.operator.product
