parameters:
    pim_enrich.form.type.product.view.class:    PimEnterprise\Bundle\EnrichBundle\Form\View\ProductFormView
    pim_enrich.controller.category_tree.class:  PimEnterprise\Bundle\EnrichBundle\Controller\CategoryTreeController
