imports:
    - { resource: '@PimEnrichBundle/Resources/config/pim.yml' }

assetic:
    bundles:
        - OroAsseticBundle
        - OroUIBundle
        - OroUserBundle
        - OroFilterBundle
        - OroNavigationBundle
        - OroWindowsBundle
        - OroEntityExtendBundle
        - OroSecurityBundle
        - PimUIBundle
        - PimCatalogBundle
        - PimEnrichBundle
        - PimEnterpriseEnrichBundle

twig:
    globals:
        bap:
            layout: PimEnterpriseEnrichBundle::base.html.twig
            start_route: oro_default
    form:
        resources:
            - 'PimEnterpriseUIBundle:Form:pimee-fields.html.twig'

fos_rest:
    exception:
        codes:
            PimEnterprise\Bundle\WorkflowBundle\Exception\PublishedProductConsistencyException: HTTP_CONFLICT
        messages:
            PimEnterprise\Bundle\WorkflowBundle\Exception\PublishedProductConsistencyException: true
