imports:
    - { resource: @PimEnrichBundle/Resources/config/pim.yml }

twig:
    form:
        resources:
            - 'PimEnterpriseUIBundle:Form:pimee-fields.html.twig'

fos_rest:
    exception:
        codes:
            PimEnterprise\Bundle\WorkflowBundle\Exception\PublishedProductConsistencyException: HTTP_CONFLICT
        messages:
            PimEnterprise\Bundle\WorkflowBundle\Exception\PublishedProductConsistencyException: true
