pim:
    resource: '@PimEnrichBundle/Resources/config/routing.yml'

pimee_product:
    resource: '@PimEnterpriseEnrichBundle/Resources/config/routing/pimee_product.yml'
    prefix: /enrich/product

pimee_locale:
    resource: '@PimEnterpriseEnrichBundle/Resources/config/routing/pimee_locale.yml'
    prefix: /configuration/locale
