parameters:
    pimee_enrich.twig.version_extension.class:                 PimEnterprise\Bundle\EnrichBundle\Twig\VersionExtension
    pimee_enrich.form.subscriber.attribute_group_rights.class: PimEnterprise\Bundle\EnrichBundle\Form\Subscriber\AttributeGroupRightsSubscriber

services:
    pimee_enrich.twig.version_extension:
        class: %pimee_enrich.twig.version_extension.class%
        tags:
            - { name: twig.extension }

    pimee_enrich.form.subscriber.attribute_group_rights:
        class: %pimee_enrich.form.subscriber.attribute_group_rights.class%
        arguments:
            - '@pimee_security.manager.attribute_group_access'
