parameters:
    pimee_enrich.twig.version_extension.class: PimEnterprise\Bundle\EnrichBundle\Twig\VersionExtension
    pimee_enrich.form.subscriber.attribute_group_permissions.class: PimEnterprise\Bundle\EnrichBundle\Form\Subscriber\AttributeGroupPermissionsSubscriber
    pimee_enrich.form.subscriber.category_permissions.class: PimEnterprise\Bundle\EnrichBundle\Form\Subscriber\CategoryPermissionsSubscriber
    pim_enrich.twig.category_extension.class:                PimEnterprise\Bundle\EnrichBundle\Twig\CategoryExtension

services:
    pimee_enrich.twig.version_extension:
        class: %pimee_enrich.twig.version_extension.class%
        tags:
            - { name: twig.extension }

    pimee_enrich.form.subscriber.attribute_group_permissions:
        class: %pimee_enrich.form.subscriber.attribute_group_permissions.class%
        arguments:
            - '@pimee_security.manager.attribute_group_access'

    pimee_enrich.form.subscriber.category_permissions:
        class: %pimee_enrich.form.subscriber.category_permissions.class%
        arguments:
            - '@pimee_security.manager.category_access'

    pimee_enrich.event_listener.propositions_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [ product ]
          - '@oro_datagrid.datagrid.request_params'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.proposition-grid, method: onBuildAfter }

    pim_enrich.twig.category_extension:
        class: %pim_enrich.twig.category_extension.class%
        arguments:
            - '@pim_catalog.manager.product_category'
            - '@pimee_workflow.manager.published_product_category'
        tags:
            - { name: twig.extension }
