parameters:
    pim_enterprise_enrich.twig.version_extension.class:           PimEnterprise\Bundle\EnrichBundle\Twig\VersionExtension
    pim_enterprise_enrich.form.type.attribute_group_rights.class: PimEnterprise\Bundle\EnrichBundle\Form\Type\AttributeGroupRightsType
    pim_enrich.form.type.attribute_group.class:                   PimEnterprise\Bundle\EnrichBundle\Form\Type\AttributeGroupType

services:
    pim_enterprise_enrich.twig.version_extension:
        class: %pim_enterprise_enrich.twig.version_extension.class%
        tags:
            - { name: twig.extension }

    pim_enterprise_enrich.form.type.attribute_group_rights:
        class: %pim_enterprise_enrich.form.type.attribute_group_rights.class%
        tags:
            - { name: form.type, alias: pim_enterprise_enrich_attribute_group_rights }
