PimEnterprise\Bundle\CatalogRuleBundle\Model\ProductCopyValueAction:
    properties:
        fromField:
           - Type:
                type: string
           - NotBlank: ~
           - Length:
               max: 255
           - \PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraints\ExistingField: ~
        toField:
           - Type:
                type: string
           - NotBlank: ~
           - Length:
               max: 255
           - \PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraints\ExistingField: ~
        fromScope:
            - Type:
                type: string
            - Length:
                max: 100
        toScope:
            - Type:
                type: string
            - Length:
                max: 100
        fromLocale:
            - Type:
                type: string
            - Length:
                max: 100
        toLocale:
            - Type:
                type: string
            - Length:
                max: 100
