PimEnterprise\Bundle\CatalogRuleBundle\Model\ProductCondition:
    properties:
        field:
           - Type:
                type: string
           - NotBlank: ~
           - Length:
               max: 255
        operator:
            - Type:
                type: string
            - NotBlank: ~
            - Length:
                max: 100
        value:
            - NotBlank: ~
        scope:
            - Type:
                type: string
            - Length:
                max: 100
        locale:
            - Type:
                type: string
            - Length:
                max: 100
