PimEnterprise\Bundle\CatalogRuleBundle\Model\ProductCopyValueAction:
    constraints:
        - \PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraints\ProductRule\ValueAction: ~
    properties:
        fromField:
           - Type:
                type: string
           - NotBlank:
                message: The key "from_field" is missing or empty.
           - Length:
               max: 255
           - \PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraints\ExistingField: ~
        toField:
           - Type:
                type: string
           - NotBlank:
                message: The key "to_field" is missing or empty.
           - Length:
               max: 255
           - \PimEnterprise\Bundle\CatalogRuleBundle\Validator\Constraints\ExistingField: ~
        fromScope:
            - Type:
                type: string
            - Length:
                max: 100
        toScope:
            - Type:
                type: string
            - Length:
                max: 100
        fromLocale:
            - Type:
                type: string
            - Length:
                max: 100
        toLocale:
            - Type:
                type: string
            - Length:
                max: 100
