parameters:
    pimee_enrich.view.tab.attributegroup_permission.template: 'PimEnrichBundle:AttributeGroup:Tab/permission.html.twig'

services:
    pimee_enrich.view.tab.attributegroup_permission_base:
        parent: pim_enrich.view.tab.base
        arguments:
            - %pimee_enrich.view.tab.attributegroup_permission.template%
            - 'tab.pim_enrich_attributegroup_edit.permission'
    pimee_enrich.view.tab.attributegroup_permission_on_form_edit:
        parent: pim_enrich.view.tab.on_form_edit
        arguments:
            - @pimee_enrich.view.tab.attributegroup_permission_base
    pimee_enrich.view.tab.attributegroup_permission:
        parent: pim_enrich.view.tab.granted
        arguments:
            - @pimee_enrich.view.tab.attributegroup_permission_on_form_edit
            - 'pimee_enrich_attribute_group_edit_permissions'
        tags:
            - { name: pim_enrich_views.tab, position: 105, identifier: pim_enrich_attributegroup_edit}
