parameters:
    pimee_filter.datasource.proposal_adapter.class:              Pim\Bundle\FilterBundle\Datasource\MongoDbOdm\OdmFilterDatasourceAdapter
    pimee_datagrid.extension.pager.proposal.pager.class:         Pim\Bundle\DataGridBundle\Extension\Pager\MongoDbOdm\Pager
    pimee_datagrid.extension.sorter.proposal.field_sorter.class: Pim\Bundle\DataGridBundle\Extension\Sorter\MongoDbOdm\FieldSorter
