parameters:
    pimee_datagrid.datasource.result_record.hydrator.product_history.class: PimEnterprise\Bundle\DataGridBundle\Datasource\ResultRecord\MongoDBODM\ProductHistoryHydrator
    pimee_datagrid.datasource.result_record.hydrator.product_draft.class:     PimEnterprise\Bundle\DataGridBundle\Datasource\ResultRecord\MongoDBODM\PropositionHydrator
