parameters:
    pimee_filter.datasource.proposition_adapter.class:              Pim\Bundle\FilterBundle\Datasource\Orm\OrmFilterDatasourceAdapter
    pimee_datagrid.extension.pager.proposition.pager.class:         Pim\Bundle\DataGridBundle\Extension\Pager\Orm\Pager
    pimee_datagrid.extension.sorter.proposition.field_sorter.class: Pim\Bundle\DataGridBundle\Extension\Sorter\Orm\FieldSorter
