parameters:
    pim_catalog.repository.product_mass_action.class: PimEnterprise\Bundle\CatalogBundle\Doctrine\MongoDBODM\ProductMassActionRepository

services:
    pim_catalog.repository.product_mass_action:
        class: %pim_catalog.repository.product_mass_action.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - %pim_catalog.entity.product.class%
            - '@pim_catalog.repository.family'
            - '@pimee_workflow.repository.published_product'

    pim_catalog.doctrine.query.filter.original_product_id:
        class: %pim_catalog.doctrine.query.filter.base.class%
        arguments:
            - @pim_catalog.context.catalog
            - []
            - ['originalProduct']
            - ['=', 'IN']
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 30 }
