pimee_workflow_proposal_approve:
    path: /{id}/approve
    defaults: { _controller: pimee_workflow.controller.proposal:approveAction }

pimee_workflow_proposal_refuse:
    path: /{id}/refuse
    defaults: { _controller: pimee_workflow.controller.proposal:refuseAction }
