PimEnterprise\Bundle\WorkflowBundle\Model\Proposition:
    type: document
    collection: pimee_workflow_product_draft
    repositoryClass: PimEnterprise\Bundle\WorkflowBundle\Doctrine\MongoDBODM\PropositionRepository
    fields:
        id:
            id: true
            generator: { strategy: AUTO }
        createdAt:
            type: date
            column: created_at
        changes:
            type: hash
        product:
            reference: true
            type: one
            targetDocument: Pim\Bundle\CatalogBundle\Model\ProductInterface
        author:
            type: string
        # Denormalize product's category ids stored for checking product ownership
        categoryIds:
            type: collection
        status:
            type: int
    indexes:
        unique_idx:
            keys:
                author: asc
                product: asc
            options:
                unique: true
                dropDups: true
                safe: true
