PimEnterprise\Bundle\WorkflowBundle\Model\PublishedAssociation:
    type: entity
    table: pimee_workflow_publishedassociation
    repositoryClass: Pim\Bundle\CatalogBundle\Doctrine\ORM\AssociationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    uniqueConstraints:
        locale_foreign_key_idx:
            columns:
                - owner_id
                - association_type_id
    manyToOne:
        associationType:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AssociationType
            joinColumns:
                association_type_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
        owner:
            targetEntity: PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProduct
            inversedBy: associations
            joinColumns:
                owner_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
    manyToMany:
        groups:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Group
            joinTable:
                name: pimee_workflow_publishedassociation_publishedgroup
                joinColumns:
                    association_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: CASCADE
        products:
            targetEntity: PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProduct
            joinTable:
                name: pimee_workflow_publishedassociation_publishedproduct
                joinColumns:
                    association_id:
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE
