PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProductMedia:
    type: embeddedDocument
    fields:
        id:
            id: true
        filename:
            type: string
        originalFilename:
            type: string
        mimeType:
            type: string
