PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProductCompleteness:
    type: entity
    table: pimee_workflow_published_product_completeness
    uniqueConstraints:
        searchunique_idx:
            columns:
                - channel_id
                - locale_id
                - product_id
    indexes:
        ratio_idx:
            columns:
                - ratio
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        ratio:
            type: integer
        missingCount:
            type: integer
            column: missing_count
        requiredCount:
            type: integer
            column: required_count
    manyToOne:
        locale:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Locale
            joinColumns:
                locale_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
        channel:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Channel
            joinColumns:
                channel_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
        product:
            targetEntity: PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProduct
            inversedBy: completenesses
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
