PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProduct:
    type: document
    repositoryClass: PimEnterprise\Bundle\WorkflowBundle\Doctrine\MongoDBODM\PublishedProductRepository
    collection: pimee_workflow_published_product
    fields:
        id:
            id: true
            generator:
                strategy: AUTO
        enabled:
            type: boolean
        created:
            type: date
        updated:
            type: date
        originalProductId:
            type: string
        family:
            type: entity
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Family
        groups:
            notSaved: true
            type: entities
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Group
            idsField: groupIds
        groupIds:
            type: collection
        categories:
            notSaved: true
            type: entities
            targetEntity: Pim\Bundle\CatalogBundle\Entity\Category
            idsField: categoryIds
        categoryIds:
            type: collection
        associations:
            embedded: true
            type: many
            targetDocument: PimEnterprise\Bundle\WorkflowBundle\Model\PublishedAssociation
        completenesses:
            embedded: true
            type: many
            targetDocument: Pim\Bundle\CatalogBundle\Model\Completeness
        values:
            embedded: true
            type: many
            targetDocument: PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProductValue
            mappedBy: entity
        normalizedData:
            type: hash
