PimEnterprise\Bundle\WorkflowBundle\Model\PublishedProductPrice:
    type: embeddedDocument
    fields:
        id:
            id: true
        data:
            type: float
        currency:
            type: string
