PimEnterprise\Bundle\CatalogBundle\Model\Proposal:
    type: entity
    table: pimee_catalog_product_proposal
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        createdAt:
            type: datetime
            column: created_at
        changes:
            type: array
        createdBy:
            type: string
    manyToOne:
        product:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductInterface
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
