connector:
    name: Akeneo Rule Engine Connector
    jobs:
        yml_rule_import:
            title: pimee_catalog_rule.jobs.yml_rule_import.title
            type:  import
            steps:
                import:
                    title: pimee_catalog_rule.jobs.yml_rule_import.import.title
                    services:
                        reader:    pim_base_connector.reader.file.yaml
                        processor: pimee_catalog_rule.processor.rule_definition.array_to_object
                        writer:    pimee_catalog_rule.writer.rule_definition.doctrine
        yml_rule_export:
            title: pimee_catalog_rule.jobs.yml_rule_export.title
            type:  export
            steps:
                export:
                    title: pimee_catalog_rule.jobs.yml_rule_export.export.title
                    services:
                        reader:    pimee_catalog_rule.reader.rule_definition.doctrine
                        processor: pimee_catalog_rule.processor.rule_definition.object_to_array
                        writer:    pimee_catalog_rule.writer.rule_definition.yaml_file
