connector:
    name: Akeneo Rule Engine Connector
    jobs:
        rule_engine:
            title: Rule engine
            type: rule_engine
            steps:
                rule_engine:
                    class: PimEnterprise\Bundle\RuleEngineBundle\Batch\RuleStep
                    title: Rule runner
                    services:
                        reader: pimee_catalog_rule.reader.product
                        runner: pimee_catalog_rule.runner.product
        yml_rule_import:
            title: pimee_catalog_rule.jobs.yml_rule_import.title
            type:  import
            steps:
                import:
                    title: pimee_catalog_rule.jobs.yml_rule_import.import.title
                    services:
                        reader:    pim_base_connector.reader.file.yaml
                        processor: pimee_catalog_rule.processor.rule_definition
                        writer:    pimee_catalog_rule.writer.doctrine.rule_definition
        yml_rule_export:
            title: pimee_catalog_rule.jobs.yml_rule_export.title
            type:  export
            steps:
                export:
                    title: pimee_catalog_rule.jobs.yml_rule_export.export.title
                    services:
                        reader:    pimee_catalog_rule.reader.rule_definition.doctrine
                        processor: pimee_catalog_rule.processor.rule_definition.object_to_array
                        writer:    pimee_catalog_rule.writer.rule_definition.yaml_file
