connector:
    name: Akeneo Rule Engine Connector
    jobs:
        rule_engine:
            title: Rule engine
            type: rule_engine
            steps:
                rule_engine:
                    class: PimEnterprise\Bundle\RuleEngineBundle\Batch\RuleStep
                    title: Rule runner
                    services:
                        reader: pimee_catalog_rule.reader.product
                        runner: pimee_catalog_rule.runner.product
