parameters:
    # import rules
    pimee_catalog_rule.processor.denormalization.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\Processor\Denormalization\RuleDefinitionProcessor
    pimee_catalog_rule.writer.doctrine.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\Writer\Doctrine\RuleDefinitionWriter
    # export rules
    pimee_catalog_rule.reader.doctrine.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\Reader\Doctrine\RuleDefinitionReader
    pimee_catalog_rule.processor.normalization.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\Processor\Normalization\RuleDefinitionProcessor
    pimee_catalog_rule.writer.yaml_file.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\Writer\YamlFile\RuleDefinitionWriter

services:
    # import rules
    pimee_catalog_rule.processor.denormalization.rule_definition:
        class: %pimee_catalog_rule.processor.denormalization.rule_definition.class%
        arguments:
            - '@akeneo_rule_engine.repository.rule_definition'
            - '@pimee_catalog_rule.denormalizer.product_rule.chained'
            - '@validator'
            - %akeneo_rule_engine.model.rule_definition.class%
            - %akeneo_rule_engine.model.rule.class%

    pimee_catalog_rule.writer.doctrine.rule_definition:
        class: %pimee_catalog_rule.writer.doctrine.rule_definition.class%
        arguments:
            - '@akeneo_rule_engine.saver.rule_definition'

    # export rules
    pimee_catalog_rule.reader.doctrine.rule_definition:
        class: %pimee_catalog_rule.reader.doctrine.rule_definition.class%
        arguments:
            - '@akeneo_rule_engine.repository.rule_definition'

    pimee_catalog_rule.processor.normalization.rule_definition:
        class: %pimee_catalog_rule.processor.normalization.rule_definition.class%
        arguments:
            - '@akeneo_rule_engine.normalizer.rule'

    pimee_catalog_rule.writer.yaml_file.rule_definition:
        class: %pimee_catalog_rule.writer.yaml_file.rule_definition.class%
