parameters:
    pimee_catalog_rule.processor.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\ProductRuleDefinitionProcessor
    pimee_catalog_rule.writer.doctrine.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionWriter
    pimee_catalog_rule.writer.yaml.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionYamlWriter
    pimee_catalog_rule.processor.yaml.rule_definition.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\YamlProcessor

services:
    pimee_catalog_rule.writer.doctrine.rule_definition:
        class: %pimee_catalog_rule.writer.doctrine.rule_definition.class%
        arguments:
          - '@pimee_rule_engine.manager.rule_definition'

    pimee_catalog_rule.writer.yaml.rule_definition:
        class: %pimee_catalog_rule.writer.yaml.rule_definition.class%

    pimee_catalog_rule.processor.rule_definition:
        class: %pimee_catalog_rule.processor.rule_definition.class%
        arguments:
            - @pimee_rule_engine.repository.rule
            - @pimee_catalog_rule.denormalizer.rule
            - @validator
            - %pimee_rule_engine.entity.rule_definition.class%
            - @pimee_catalog_rule.serializer.rule_content
            - %pimee_rule_engine.entity.rule.class%

    pimee_catalog_rule.processor.yaml.rule_definition:
        class: %pimee_catalog_rule.processor.yaml.rule_definition.class%
        arguments:
            - @pimee_catalog_rule.serializer.rule_content

