parameters:
    # import rules
    pimee_catalog_rule.processor.rule_definition.array_to_object.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\ProductRuleDefinitionArrayToObjectProcessor
    pimee_catalog_rule.writer.rule_definition.doctrine.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionDoctrineWriter
    # export rules
    pimee_catalog_rule.reader.rule_definition.doctrine.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionDoctrineReader
    pimee_catalog_rule.processor.rule_definition.object_to_array.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionObjectToArrayProcessor
    pimee_catalog_rule.writer.rule_definition.yaml_file.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleDefinitionYamlFileWriter

services:
    # import rules
    pimee_catalog_rule.processor.rule_definition.array_to_object:
        class: %pimee_catalog_rule.processor.rule_definition.array_to_object.class%
        arguments:
            - @akeneo_rule_engine.repository.rule_definition
            - @akeneo_rule_engine.denormalizer.rule
            - @validator
            - %akeneo_rule_engine.model.rule_definition.class%
            - %akeneo_rule_engine.model.rule.class%

    pimee_catalog_rule.writer.rule_definition.doctrine:
        class: %pimee_catalog_rule.writer.rule_definition.doctrine.class%
        arguments:
          - '@akeneo_rule_engine.saver.rule_definition'

    # export rules
    pimee_catalog_rule.reader.rule_definition.doctrine:
        class: %pimee_catalog_rule.reader.rule_definition.doctrine.class%
        arguments:
            - @akeneo_rule_engine.repository.rule_definition

    pimee_catalog_rule.processor.rule_definition.object_to_array:
        class: %pimee_catalog_rule.processor.rule_definition.object_to_array.class%
        arguments:
            - @pimee_catalog_rule.normalizer.rule_content

    pimee_catalog_rule.writer.rule_definition.yaml_file:
        class: %pimee_catalog_rule.writer.rule_definition.yaml_file.class%
