parameters:
    pimee_catalog_rule.controller.rule.class: PimEnterprise\Bundle\CatalogRuleBundle\Controller\RuleController

services:
    pimee_catalog_rule.controller.rule:
        scope: request
        class: %pimee_catalog_rule.controller.rule.class%
        arguments:
            - '@pimee_catalog_rule.manager.rule_relation'
            - '@pimee_rule_engine.remover.rule_definition'
            - '@pimee_rule_engine.repository.rule_definition'
            - '@pim_internal_api_serializer'
            - '%pim_catalog.entity.attribute.class%'
