services:
    pimee_catalog_rule.saver.rule_relation:
        class: %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pimee_catalog_rule.entity.rule_relation.class%

    pimee_catalog_rule.remover.rule_relation:
        class: %pim_catalog.remover.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pimee_catalog_rule.entity.rule_relation.class%
