parameters:
    pimee_catalog_rule.applier.product.class: PimEnterprise\Bundle\CatalogRuleBundle\Engine\ProductRuleApplier
    pimee_catalog_rule.builder.product.class: PimEnterprise\Bundle\CatalogRuleBundle\Engine\ProductRuleBuilder
    pimee_catalog_rule.selector.product.class: PimEnterprise\Bundle\CatalogRuleBundle\Engine\ProductRuleSelector

services:
    pimee_catalog_rule.builder.product:
        class: %pimee_catalog_rule.builder.product.class%
        arguments:
            - '@pimee_catalog_rule.denormalizer.product_rule.chained'
            - '@event_dispatcher'
            - '@validator'
            - %akeneo_rule_engine.model.rule.class%

    pimee_catalog_rule.selector.product:
        class: %pimee_catalog_rule.selector.product.class%
        arguments:
            - '@pim_catalog.doctrine.query.product_query_factory'
            - '@pim_catalog.repository.product'
            - '@event_dispatcher'
            - %akeneo_rule_engine.model.rule_subject_set.class%

    pimee_catalog_rule.applier.product:
        class: %pimee_catalog_rule.applier.product.class%
        arguments:
            - '@pim_catalog.updater.product'
            - '@pim_validator'
            - '@pim_catalog.saver.product'
            - '@event_dispatcher'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_versioning.manager.version'
            - '@pim_transform.cache.product_cache_clearer'
            - '@translator'
            - %akeneo_rule_engine.model.rule_definition.class%
