parameters:
    pimee_catalog_rule.event_subscriber.attribute.class: PimEnterprise\Bundle\CatalogRuleBundle\EventSubscriber\RemoveLinkedResourceSubscriber

services:
    pimee_catalog_rule.event_subscriber.attribute:
        class: %pimee_catalog_rule.event_subscriber.attribute.class%
        arguments:
            - '@pimee_catalog_rule.manager.rule_linked_resource'
            - '@pimee_catalog_rule.repository.rule_linked_resource'
        tags:
            - { name: kernel.event_subscriber}
