parameters:
    pimee_catalog_rule.event_subscriber.linked_resource.class: PimEnterprise\Bundle\CatalogRuleBundle\EventSubscriber\LinkedResourceSubscriber

services:
    pimee_catalog_rule.event_subscriber.linked_resource:
        class: %pimee_catalog_rule.event_subscriber.linked_resource.class%
        arguments:
            - '@pimee_catalog_rule.manager.rule_linked_resource'
            - '@pimee_catalog_rule.repository.rule_linked_resource'
            - '@pimee_catalog_rule.selector.product'
            - '@pimee_catalog_rule.loader.product'
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: kernel.event_subscriber}
