parameters:
    pimee_catalog_rule.reader.product.class: PimEnterprise\Bundle\RuleEngineBundle\Batch\RuleReader

services:
    # TODO: should be put in another branch, it's used only for batch
    # TODO: should be in connector_steps.yml
    # TODO: should be renamed
    pimee_catalog_rule.reader.product:
        class: '%pimee_catalog_rule.reader.product.class%'
        arguments:
            - @pimee_rule_engine.repository.rule_definition

