parameters:
    pimee_catalog_rule.reader.product.class: PimEnterprise\Bundle\RuleEngineBundle\Batch\RuleReader
    pimee_catalog_rule.reader.class: PimEnterprise\Bundle\CatalogRuleBundle\Connector\RuleReader

services:
    pimee_catalog_rule.reader.product:
        class: '%pimee_catalog_rule.reader.product.class%'
        arguments:
            - @pimee_rule_engine.repository.rule

    pimee_catalog_rule.reader:
        class: '%pimee_catalog_rule.reader.class%'
        arguments:
            - @pimee_rule_engine.repository.rule
