config:
    paths:
        pimee/catalogrule/itemtableview: pimenterprisecatalogrule/js/itemtableview
        pimee/catalogrule/ruleitemview:  pimenterprisecatalogrule/js/ruleitemview
        pimee/catalogrule/itemview:      pimenterprisecatalogrule/js/itemview
        pimee/catalogrule/ruletableview: pimenterprisecatalogrule/js/ruletableview
