pimee_catalog_rule_index:
    path: /rules/{resourceType}/{resourceId}
    defaults: { _controller: pimee_catalog_rule.controller.rule:indexAction }
    requirements:
        resourceType: '[0-9a-z]+'
        resourceId: '\d+'
    methods: [GET]
