parameters:
    pimee_catalog_rule.runner.product.class: PimEnterprise\Bundle\CatalogRuleBundle\Runner\ProductRuleRunner

services:
    pimee_catalog_rule.runner.product:
        class: %pimee_catalog_rule.runner.product.class%
        arguments:
            - @pimee_catalog_rule.loader.product
            - @pimee_catalog_rule.selector.product
            - @pimee_catalog_rule.applier.product
        tags:
            - { name: pimee_rule_engine.runner }
