parameters:
    pimee_catalog_rule.denormalizer.product_rule.class:                   Akeneo\Bundle\RuleEngineBundle\Denormalizer\RuleDenormalizer
    pimee_catalog_rule.denormalizer.product_rule.content.class:           PimEnterprise\Bundle\CatalogRuleBundle\Denormalizer\ProductRule\ContentDenormalizer
    pimee_catalog_rule.denormalizer.product_rule.set_value_action.class:  PimEnterprise\Bundle\CatalogRuleBundle\Denormalizer\ProductRule\SetValueActionDenormalizer
    pimee_catalog_rule.denormalizer.product_rule.copy_value_action.class: PimEnterprise\Bundle\CatalogRuleBundle\Denormalizer\ProductRule\CopyValueActionDenormalizer
    pimee_catalog_rule.denormalizer.product_rule.condition.class:         PimEnterprise\Bundle\CatalogRuleBundle\Denormalizer\ProductRule\ConditionDenormalizer

    pimee_catalog_rule.normalizer.product_rule.content.class:             PimEnterprise\Bundle\CatalogRuleBundle\Normalizer\ProductRule\ContentNormalizer
    pimee_catalog_rule.normalizer.product_rule.set_value_action.class:    PimEnterprise\Bundle\CatalogRuleBundle\Normalizer\ProductRule\SetValueActionNormalizer
    pimee_catalog_rule.normalizer.product_rule.copy_value_action.class:   PimEnterprise\Bundle\CatalogRuleBundle\Normalizer\ProductRule\CopyValueActionNormalizer
    pimee_catalog_rule.normalizer.product_rule_condition.class:           PimEnterprise\Bundle\CatalogRuleBundle\Normalizer\ProductRule\ConditionNormalizer

services:
    pimee_catalog_rule.denormalizer.product_rule:
        class: %pimee_catalog_rule.denormalizer.product_rule.class%
        arguments:
            - @pimee_catalog_rule.denormalizer.product_rule.content
            - %akeneo_rule_engine.model.rule.class%
            - %akeneo_rule_engine.model.rule_definition.class%
            - 'product'

    pimee_catalog_rule.denormalizer.product_rule.content:
        class: %pimee_catalog_rule.denormalizer.product_rule.content.class%
        arguments:
            - @pimee_catalog_rule.denormalizer.product_rule.condition
            - @pimee_catalog_rule.denormalizer.product_rule.set_value_action
            - @pimee_catalog_rule.denormalizer.product_rule.copy_value_action
            - %akeneo_rule_engine.model.rule.class%

    pimee_catalog_rule.normalizer.product_rule.content:
        class: %pimee_catalog_rule.normalizer.product_rule.content.class%
        arguments:
            - @pimee_catalog_rule.normalizer.product_rule_condition
            - @pimee_catalog_rule.normalizer.product_rule.set_value_action
            - @pimee_catalog_rule.normalizer.product_rule.copy_value_action

    pimee_catalog_rule.normalizer.product_rule_condition:
        class: %pimee_catalog_rule.normalizer.product_rule_condition.class%

    pimee_catalog_rule.denormalizer.product_rule.condition:
        class: %pimee_catalog_rule.denormalizer.product_rule.condition.class%
        arguments:
            - %pimee_catalog_rule.model.product_condition.class%

    pimee_catalog_rule.normalizer.product_rule.set_value_action:
        class: %pimee_catalog_rule.normalizer.product_rule.set_value_action.class%

    pimee_catalog_rule.denormalizer.product_rule.set_value_action:
        class: %pimee_catalog_rule.denormalizer.product_rule.set_value_action.class%
        arguments:
            - %pimee_catalog_rule.model.set_value_action.class%

    pimee_catalog_rule.normalizer.product_rule.copy_value_action:
        class: %pimee_catalog_rule.normalizer.product_rule.copy_value_action.class%

    pimee_catalog_rule.denormalizer.product_rule.copy_value_action:
        class: %pimee_catalog_rule.denormalizer.product_rule.copy_value_action.class%
        arguments:
            - %pimee_catalog_rule.model.copy_value_action.class%
