parameters:
    pimee_catalog_rule.serializer.rule_content.class:              PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductRuleContentJsonSerializer
    pimee_catalog_rule.denormalizer.rule.class:                    PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductRuleDenormalizer
    pimee_catalog_rule.normalizer.rule.class:                      PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductRuleNormalizer
    pimee_catalog_rule.normalizer.product_set_value_action.class:  PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductSetValueActionNormalizer
    pimee_catalog_rule.normalizer.product_copy_value_action.class: PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductCopyValueActionNormalizer
    pimee_catalog_rule.normalizer.product_rule_condition.class:    PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductRuleConditionNormalizer

services:
    pimee_catalog_rule.serializer.rule_content:
        class: %pimee_catalog_rule.serializer.rule_content.class%
        arguments:
            - @pimee_catalog_rule.normalizer.product_rule_condition
            - @pimee_catalog_rule.normalizer.product_set_value_action
            - @pimee_catalog_rule.normalizer.product_copy_value_action

    pimee_catalog_rule.denormalizer.rule:
        class: %pimee_catalog_rule.denormalizer.rule.class%
        arguments:
            - @pimee_catalog_rule.normalizer.product_rule_condition
            - @pimee_catalog_rule.normalizer.product_set_value_action
            - @pimee_catalog_rule.normalizer.product_copy_value_action
            - %pimee_rule_engine.entity.rule.class%
            - %pimee_rule_engine.entity.rule_definition.class%

    pimee_catalog_rule.normalizer.rule:
        class: %pimee_catalog_rule.normalizer.rule.class%
        arguments:
            - @pimee_catalog_rule.serializer.rule_content
            - @pimee_catalog_rule.normalizer.product_rule_condition
            - @pimee_catalog_rule.normalizer.product_set_value_action
            - @pimee_catalog_rule.normalizer.product_copy_value_action

    pimee_catalog_rule.normalizer.product_rule_condition:
        class: %pimee_catalog_rule.normalizer.product_rule_condition.class%
        arguments:
            - %pimee_catalog_rule.model.product_condition.class%

    pimee_catalog_rule.normalizer.product_set_value_action:
        class: %pimee_catalog_rule.normalizer.product_set_value_action.class%
        arguments:
            - %pimee_catalog_rule.model.set_value_action.class%

    pimee_catalog_rule.normalizer.product_copy_value_action:
        class: %pimee_catalog_rule.normalizer.product_copy_value_action.class%
        arguments:
            - %pimee_catalog_rule.model.copy_value_action.class%
