parameters:
    pimee_catalog_rule.serializer.rule_content.class: PimEnterprise\Bundle\CatalogRuleBundle\Serializer\ProductRuleContentJsonSerializer

services:
    pimee_catalog_rule.serializer.rule_content:
        class: %pimee_catalog_rule.serializer.rule_content.class%
        arguments:
            - %pimee_catalog_rule.model.product_condition.class%
            - %pimee_catalog_rule.model.copy_value_action.class%
            - %pimee_catalog_rule.model.set_value_action.class%
