parameters:
    akeneo_rule_engine.runner.chained.class: Akeneo\Bundle\RuleEngineBundle\Runner\ChainedRunner

services:
    akeneo_rule_engine.runner.chained:
        class: %akeneo_rule_engine.runner.chained.class%

    akeneo_rule_engine.runner.batch:
        abstract: true
        calls:
            - [ setRootDir, [%kernel.root_dir%]]
            - [ setEnvironment, [%kernel.environment%]]
            - [ setJobCode, ['rule_engine']]
