parameters:
    pim_catalog.manager.product_mass_action.class: PimEnterprise\Bundle\CatalogBundle\Manager\ProductMassActionManager
    pim_catalog.manager.category.class: PimEnterprise\Bundle\CatalogBundle\Manager\CategoryManager
    pim_catalog.manager.product_category.class: PimEnterprise\Bundle\CatalogBundle\Manager\ProductCategoryManager
    pim_catalog.manager.media.class: PimEnterprise\Bundle\CatalogBundle\Manager\MediaManager

services:
    pim_catalog.manager.product_mass_action:
        class: %pim_catalog.manager.product_mass_action.class%
        arguments:
            - '@pim_catalog.repository.product_mass_action'
            - '@pim_catalog.repository.attribute'
            - '@pimee_security.repository.attribute_group_access'
            - '@security.context'

    pim_catalog.manager.category:
        class: %pim_catalog.manager.category.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.category.class%
            - '@event_dispatcher'
            - '@pimee_security.repository.category_access'
            - '@security.context'

    pim_catalog.manager.product_category:
        class: %pim_catalog.manager.product_category.class%
        arguments:
            - '@pim_catalog.repository.product_category'
            - '@pim_catalog.repository.category'
            - '@security.context'
            - '@pimee_security.repository.category_access'

    pim_catalog.manager.media:
        class: %pim_catalog.manager.media.class%
        arguments:
            - '@pim_filesystem'
            - %upload_dir%
            - '@pim_catalog.factory.media'
