parameters:
    pim_catalog.persister.product.class: PimEnterprise\Bundle\CatalogBundle\Persistence\ProposalPersister
    pim_catalog.factory.proposal.class: PimEnterprise\Bundle\CatalogBundle\Factory\ProposalFactory
    pim_catalog.persister.product_changes_provider.class: PimEnterprise\Bundle\CatalogBundle\Persistence\ORM\EntityChangesProvider

services:
    pim_catalog.persister.product:
        class: %pim_catalog.persister.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_catalog.manager.completeness'
            - '@security.context'
            - '@pim_catalog.factory.proposal'
            - '@pim_catalog.persister.product_changes_provider'

    pim_catalog.factory.proposal:
        public: false
        class: %pim_catalog.factory.proposal.class%

    pim_catalog.persister.product_changes_provider:
        public: false
        class: %pim_catalog.persister.product_changes_provider.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_serializer'
