parameters:
    pim_catalog.persister.product.class: PimEnterprise\Bundle\CatalogBundle\Persistence\ProposalPersister
    pimee_catalog.factory.proposal.class: PimEnterprise\Bundle\CatalogBundle\Factory\ProposalFactory
    pimee_catalog.persister.product_changes_provider.class: PimEnterprise\Bundle\CatalogBundle\Persistence\ProductChangesProvider
    pimee_catalog.entity.proposal.class: PimEnterprise\Bundle\CatalogBundle\Model\Proposal

services:
    pim_catalog.persister.product:
        class: %pim_catalog.persister.product.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_catalog.manager.completeness'
            - '@security.context'
            - '@pimee_catalog.factory.proposal'
            - '@pimee_catalog.persister.product_changes_provider'

    pimee_catalog.factory.proposal:
        public: false
        class: %pimee_catalog.factory.proposal.class%

    pimee_catalog.persister.product_changes_provider:
        public: false
        class: %pimee_catalog.persister.product_changes_provider.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'
            - '@pim_serializer'
