parameters:
    pimee_security.controller.role_category.class: PimEnterprise\Bundle\SecurityBundle\Controller\RoleCategoryController

services:
    pimee_security.controller.role_category:
        scope: request
        class: %pimee_security.controller.role_category.class%
        arguments:
            - '@router'
            - '@pim_catalog.manager.category'
            - '@pimee_security.manager.category_ownership'
