parameters:
    pimee_security.event_listener.disable_product_value_form.class: PimEnterprise\Bundle\SecurityBundle\EventListener\DisableProductValueFieldListener
    pimee_security.event_listener.product.class:                    PimEnterprise\Bundle\SecurityBundle\EventListener\ProductListener
    pimee_security.event_listener.job_permissions.class:            PimEnterprise\Bundle\SecurityBundle\EventListener\JobPermissionsListener
    pimee_security.event_listener.add_owner_roles_parameter.class:  PimEnterprise\Bundle\SecurityBundle\EventListener\AddOwnerRolesParameterListener
    pimee_security.event_listener.add_category_permissions.class:   PimEnterprise\Bundle\SecurityBundle\EventListener\AddCategoryPermissionsListener

services:
    pimee_security.event_listener.disable_product_value_form:
        class: %pimee_security.event_listener.disable_product_value_form.class%
        arguments:
            - '@security.context'
        tags:
            - { name: kernel.event_subscriber }

    pimee_security.event_listener.product:
        class: %pimee_security.event_listener.product.class%
        arguments:
            - '@security.context'
            - '@pim_user.context.user'
        tags:
            - { name: kernel.event_subscriber }

    pimee_security.event_listener.job_permissions:
        class: %pimee_security.event_listener.job_permissions.class%
        arguments:
            - '@security.context'
        tags:
            - { name: kernel.event_subscriber }

    pimee_security.event_listener.add_owner_roles_parameter:
        class: %pimee_security.event_listener.add_owner_roles_parameter.class%
        arguments:
            - '@pimee_security.repository.category_access'
            - '@pim_user.context.user'
        tags:
            - { name: kernel.event_subscriber }

    pimee_security.event_listener.add_category_permissions:
        class: %pimee_security.event_listener.add_category_permissions.class%
        arguments:
            - '@pimee_security.manager.category_access'
        tags:
            - { name: kernel.event_subscriber }
