parameters:
    pimee_security.voter.attribute_group.class: PimEnterprise\Bundle\SecurityBundle\Voter\AttributeGroupVoter
    pimee_security.voter.category.class: PimEnterprise\Bundle\SecurityBundle\Voter\CategoryVoter
    pimee_security.voter.product.class: PimEnterprise\Bundle\SecurityBundle\Voter\ProductVoter
    pimee_security.voter.job_profile.class: PimEnterprise\Bundle\SecurityBundle\Voter\JobProfileVoter
    pimee_security.voter.product_ownership.class: PimEnterprise\Bundle\SecurityBundle\Voter\ProductOwnershipVoter

services:
    pimee_security.voter.attribute_group:
        class: %pimee_security.voter.attribute_group.class%
        arguments:
            - '@pimee_security.manager.attribute_group_access'
        tags:
            - { name: security.voter }

    pimee_security.voter.category:
        class: %pimee_security.voter.category.class%
        arguments:
            - '@pimee_security.manager.category_access'
        tags:
            - { name: security.voter }

    pimee_security.voter.product:
        class: %pimee_security.voter.product.class%
        arguments:
            - '@pimee_security.repository.category_access'
        tags:
            - { name: security.voter }

    pimee_security.voter.job_profile:
        class: %pimee_security.voter.job_profile.class%
        arguments:
            - '@pimee_security.manager.job_profile_access'
        tags:
            - { name: security.voter }

    pimee_security.voter.product_ownership:
        class: %pimee_security.voter.product_ownership.class%
        arguments:
            - '@pimee_security.repository.category_ownership'
        tags:
            - { name: security.voter }
