parameters:
    pimee_security.voter.attribute_group.class: PimEnterprise\Bundle\SecurityBundle\Voter\AttributeGroupVoter

services:
    pimee_security.voter.attribute_group_voter:
        class: %pimee_security.voter.attribute_group.class%
        arguments:
            - '@pimee_security.manager.attribute_group_access'
        tags:
            - { name: security.voter }
