pim_pdf_generator_generate_product_pdf:
    path: /{id}/generate-pdf
    defaults: { _controller: pimee_pdf_generator.controller.product:generatePdfAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET]
